// §7 Tier 3 — Output + Advanced (8 tools): inspect/preview, export, editor link,
// and the four advanced subsystems (templates, reports, presentations, animation)
// each folded into ONE multiplexed tool with an `op` discriminator. Capability is
// identical to the old per-tool surface — only the tool count shrank.
import type { ToolDefinition } from '../types';

export const TIER3_TOOLS: ToolDefinition[] = [
  {
    name: 'render_preview',
    description: 'Render the design to a PNG and return it INLINE as an image so you can SEE what you produced (no file written). Use it to visually verify a composition or confirm a fix — pair with diagnose_design. Foreground charts/KPIs that need a browser still only appear in the editor; everything else (shapes, patterns, text, fills) rasterizes here. COST: the preview is downscaled to a 960px longest edge by default (~a quarter of the image tokens of a full-size render) — enough to judge layout, overlap, hierarchy and colour. The response quotes `est_image_tokens` so you can budget a verification loop; pass full:true (or an explicit scale) only when you need to read fine copy.',
    inputSchema: {
      type: 'object',
      properties: {
        design_path:  { type: 'string', description: 'Path to .design.yaml' },
        project_path: { type: 'string', description: 'Project dir — enables relative design_path' },
        page_id:      { type: 'string', description: 'Carousel: preview one page (omit = first page)' },
        scale:        { type: 'number', description: 'Raster scale 0.5–2 — setting it opts out of the cheap default and renders at that scale' },
        max_edge:     { type: 'number', description: 'Longest edge in px for the cheap default (default 960)', default: 960 },
        full:         { type: 'boolean', description: 'Full canvas resolution — costs ~4× the tokens of the default', default: false },
        changed_only: { type: 'boolean', description: 'MULTI-PAGE RE-CHECK: render only the pages whose rendered output actually moved since the last preview, in ONE call. Without it, verifying an 8-page deck after a one-page edit costs 8 calls and 8 images. Pages that render byte-identically are named and skipped, not charged for. The first call on a design has no baseline, so every page counts as a first look; the next one skips whatever has not moved. Ignored with page_id or on a single-page design.', default: false },
      },
      required: ['design_path'],
    },
  },
  {
    name: 'diagnose_design',
    description: 'Built-in troubleshooter — scans a design for problems the model is blind to and returns structured findings with fixes: off-canvas layers, collisions/overlap pile-ups, near-miss MISALIGNMENT (edges off by a few px), tiny text, low-contrast/invisible text, missing background, plus quality critique (weak hierarchy, accent sprawl, crowded margins). For a design shaped like an IDENTITY MARK (single page, roughly square, <=1200px, few layers) it also returns `mark`: optical_center (centroid-of-ink vs bounding-box centre — box-centring is what makes a play triangle look pushed left), scale_survival (rendered at 16/24/32/64/128/512px, reporting where detail collapses), contrast against white/black/mid-grey, and a clearspace rule derived from the mark\'s own stroke width. It MEASURES a mark you drew; it never generates one. See get_engine_guide(section:"marks"). Run it after composing and before seal_design; fix the errors/warnings, then render_preview to confirm. SELF-HEAL: pass heal:true and it becomes a LOOP — diagnose, fix, re-diagnose, repeat until clean or until a pass changes nothing (progress is the stop condition, not a round count). It fixes SPATIAL CORRECTNESS and LEGIBILITY only: a preset whose content leaves the canvas is re-laid out from its stored spec at the size it actually has, stranded layers come back on-canvas, sub-14px text is raised, a missing ground is filled, invisible text is re-lit, positionless layers are flowed. It deliberately does NOT touch palette, hierarchy, composition or copy — those come back as `for_you_to_judge`, because a loop that re-made aesthetic decisions would converge every design on one look. The reply separates what it fixed, what it COULD have fixed but could not (`could_not_fix` — usually too much content for the canvas), and what is yours to decide. Add dry_run:true to see the plan first.',
    inputSchema: {
      type: 'object',
      properties: {
        design_path:  { type: 'string', description: 'Path to .design.yaml' },
        project_path: { type: 'string', description: 'Project dir — enables relative design_path' },
        page_id:      { type: 'string', description: 'Carousel: diagnose one page (omit = all pages)' },
        heal:         { type: 'boolean', description: 'Run the self-heal LOOP instead of just reporting: fix what is mechanically fixable, re-diagnose, repeat.', default: false },
        max_rounds:   { type: 'number', description: 'heal only — cap the loop (default 3, max 5). It stops early as soon as a pass fixes nothing.', default: 3 },
        dry_run:      { type: 'boolean', description: 'heal only — report the fixes it would apply without writing.' },
      },
      required: ['design_path'],
    },
  },
  {
    name: 'export_design',
    description: 'Export a design to SVG, PNG, PDF, HTML or PPTX (all produce real files). A carousel exports one file per page (`<name>-p1.svg`, `-p2.svg`, …); output_paths lists them. pdf is a true VECTOR PDF: text is embedded as real, selectable/copy-paste glyphs that stay crisp at any zoom, drawn over a high-DPI raster for backgrounds/gradients/effects, with clickable links — no Puppeteer/Chromium needed. pptx is a PowerPoint deck — one full-bleed image slide per page (pixel-faithful; opens in PowerPoint/Keynote/Slides as an editable container). For an INTERACTIVE report use report(op:export); for a presentation HTML/video use presentation(op:export) / animation(op:export).',
    inputSchema: {
      type: 'object',
      properties: {
        design_path:  { type: 'string', description: 'Path to .design.yaml' },
        format:       { type: 'string', enum: ['svg', 'html', 'pdf', 'png', 'pptx'] },
        output_path:  { type: 'string', description: 'Output path (auto-derived if omitted)' },
        project_path: { type: 'string', description: 'Project dir — enables relative design_path' },
        scale:        { type: 'number', description: 'Scale factor 1–3', default: 2 },
        force:        { type: 'boolean', description: 'Re-render even if this exact export was already produced. A repeat with the same design, format, scale and destination is answered from disk instead of rendered again (single-file formats), so a retry after a timeout does not redo finished work. An export killed mid-render records nothing and is always redone.', default: false },
      },
      required: ['design_path', 'format'],
    },
  },
  {
    name: 'open_in_editor',
    description: 'Return a clickable, token-embedded URL that opens a design in the Folio editor (live-refreshes as later tools edit the file). NOTE: create_design/append_page/seal_design/export_design already return this as open_url — only call this to re-open, focus a page, or open the editor home.',
    inputSchema: {
      type: 'object',
      properties: {
        design_path:  { type: 'string',  description: 'Path to .design.yaml — omit to open the editor at its home page' },
        project_path: { type: 'string',  description: 'Project dir for resolving relative design_path' },
        editor_url:   { type: 'string',  description: 'Override editor base URL (default: $FOLIO_EDITOR_URL or http://localhost:4173)' },
        page:         { type: 'number',  description: 'Page index to focus (1-based)' },
      },
      required: [],
    },
  },
  {
    name: 'templates',
    description: 'Built-in template catalog + reusable components — pick `op`:\n• list — browse the 432 built-in catalog templates (same as the editor Catalog); slim metadata {id,name,type,tags,width,height,slots,themeRef}; filter search/tag/limit. Feed a returned id straight to op:slots / op:inject.\n• slots — list injectable slots (paths/types/hints) of a template (req: template_path = a real .template.yaml path OR a built-in catalog id).\n• inject — fill slot values → a new .design.yaml (req: template_path, slots map; a built-in writes into the projects dir).\n• export — turn a sealed design into a reusable .template.yaml skeleton with named slots (req: design_path).\n• save_component — extract layers into a REUSABLE .component.yaml + replace them with an instance (req: design_path, layer_ids, component_name, project_path). Every text layer becomes a named {{slot}} with its current copy as the default, so the next instance can carry different content — that is what makes it a component rather than a copy-paste. Pass auto_slots:false to freeze the copy instead.\n• components — what this project can compose FROM: each saved component with its id, slots, variants and layer count (req: project_path). Without this the component store is write-only — place one with {type:\"component\", ref, pos, slots:{…}}.\n• batch — generate N designs from one template + an array of slot objects (req: project_path, template_id = a built-in catalog id OR a project .template.yaml id OR a design name to clone, slots_array).',
    inputSchema: {
      type: 'object',
      properties: {
        op:             { type: 'string', enum: ['list', 'slots', 'inject', 'export', 'save_component', 'components', 'batch'], description: 'Which template/component action to run.' },
        search:         { type: 'string', description: 'op:list — free-text match over id/name/tags.' },
        tag:            { type: 'string', description: 'op:list — exact tag filter (e.g. "poster", "resume").' },
        limit:          { type: 'number', description: 'op:list — max results (default 60, max 300).' },
        template_path:  { type: 'string', description: 'op:slots/inject — a real .template.yaml path OR a built-in catalog id / filename (see op:list).' },
        slots:          { type: 'object', description: 'op:inject — map of slot_id → value.', properties: {} },
        output_path:    { type: 'string', description: 'op:inject/export — output path (auto if omitted).' },
        design_path:    { type: 'string', description: 'op:export/save_component — source .design.yaml.' },
        project_path:   { type: 'string', description: 'Project dir (op:export/save_component/components/batch).' },
        auto_slots:     { type: 'boolean', description: 'op:save_component — turn each text layer into a named slot (default true). false freezes the copy.', default: true },
        layer_ids:      { type: 'array', description: 'op:save_component — layer IDs to extract.', items: { type: 'string' } },
        component_name: { type: 'string', description: 'op:save_component — name for the new component.' },
        template_id:    { type: 'string', description: 'op:batch — a built-in catalog id, a project .template.yaml id, or a design name in the project to clone.' },
        slots_array:    { type: 'array', description: 'op:batch — one slot object per design.', items: { type: 'object' } },
      },
      required: ['op'],
    },
  },
  {
    name: 'report',
    description: 'Interactive data-report subsystem (type:report designs) — pick `op`:\n• generate — scaffold a report with pages/nav/optional data; layout:"flow" = responsive 12-col interactive dashboard (set accent + font_heading/font_body) (req: project_path, name, pages).\n• customize — RESTYLE a report in place instead of regenerating it (req: design_path, changes). Merges into the report settings — layout, nav, accent, max_width, font_heading/font_body — and {width,height} re-shapes the canvas, re-laying out every preset from its stored spec rather than stretching it. Regenerating would discard everything composed since; this keeps it. Objects merge key by key, arrays replace, null deletes; dry_run:true shows the diff.\n• bind_data — attach/update inline datasets for $data.* / $agg.* expressions (req: design_path, datasets:[{id,rows[]}]).\n• validate — lint cross-refs (charts/tables/filters resolve to real datasets+fields, buttons open real modals) BEFORE export; returns {ok,errors,warnings} (req: design_path).\n• export — assemble into a self-contained interactive HTML; returns view_url (the real result to give the user) + edit_url (req: design_path).\n• formula — store state/data context for =expr bindings on a design (req: design_path).\n• debug — evaluate one =formula against a context and return the typed result (req: formula).',
    inputSchema: {
      type: 'object',
      properties: {
        op:           { type: 'string', enum: ['generate', 'customize', 'bind_data', 'validate', 'export', 'formula', 'debug'], description: 'Which report action to run.' },
        project_path: { type: 'string', description: 'Project dir (op:generate; resolves relative design_path elsewhere).' },
        name:         { type: 'string', description: 'op:generate — report name.' },
        layout:       { type: 'string', enum: ['paged', 'scroll', 'tabs', 'sidebar', 'flow'], default: 'paged', description: 'op:generate — flow = responsive 12-col interactive grid.' },
        nav_type:     { type: 'string', enum: ['sidebar', 'topbar', 'tabs', 'dots'], default: 'sidebar', description: 'op:generate — navigation style.' },
        pages:        { type: 'array', description: 'op:generate — [{id?, label}] page specs. OPTIONAL: omit for a flow/scroll report, which is one continuous scrolling document and gets a single page automatically.', items: { type: 'object' } },
        width:        { type: 'number', default: 1080, description: 'op:generate — canvas width.' },
        height:       { type: 'number', default: 1080, description: 'op:generate — canvas height.' },
        data_sources: { type: 'array', description: 'op:generate — optional inline/json/csv data sources.', items: { type: 'object' } },
        max_width:    { type: 'number', description: 'op:generate (flow) — centered container max width px (default 1200).' },
        accent:       { type: 'string', description: 'op:generate (flow) — accent color seeding charts/links/active states.' },
        font_heading: { type: 'string', description: 'op:generate (flow) — heading font family (Google font name).' },
        font_body:    { type: 'string', description: 'op:generate (flow) — body font family (Google font name).' },
        design_path:  { type: 'string', description: 'op:customize/bind_data/validate/export/formula/debug — the .design.yaml.' },
        changes:      { type: 'object', description: 'op:customize — report settings to merge (layout, navigation, accent, max_width, font_heading, font_body), plus width/height to re-shape the canvas. Only what you want different.', properties: {} },
        dry_run:      { type: 'boolean', description: 'op:customize — return the diff without writing.' },
        datasets:     { type: 'array', description: 'op:bind_data — [{id, rows[]}].', items: { type: 'object' } },
        output_path:  { type: 'string', description: 'op:export — output .html path (auto if omitted).' },
        theme:        { type: 'string', enum: ['light', 'dark'], default: 'dark', description: 'op:export — report theme.' },
        state:        { type: 'object', description: 'op:formula/debug — state variables.', properties: {} },
        data:         { type: 'object', description: 'op:formula/debug — data variables.', properties: {} },
        formula:      { type: 'string', description: 'op:debug — formula string starting with =.' },
      },
      required: ['op'],
    },
  },
  {
    name: 'presentation',
    description: 'Slide presentations + live presenting/collab — pick `op`:\n• create — scaffold a presentation design (1920×1080) with slides + transition (req: project_path, name, pages:[{label,notes?}]).\n• customize — RESTYLE or RE-SHAPE a deck in place instead of recreating it (req: design_path, changes). Merges into the presentation settings — theme, transition, auto_advance, controls, aspect_ratio — and {width,height} re-shapes every slide: presets re-EXPAND into the new page box from their stored spec (a real re-layout, not a stretch), hand-placed layers scale and centre. This is how a 1920×1080 deck becomes a 1080×1350 carousel without rebuilding it. dry_run:true shows the diff.\n• export — assemble a presentation/carousel/motion into a self-contained HTML presenter with transitions + keyboard nav (req: design_path).\n• remote — generate a remote-clicker setup: client JS + curl commands to drive slides over HTTP (opt: port, design_path).\n• collab — generate a collaborative-editing SSE file-watch server for multi-user sync (req: design_path).',
    inputSchema: {
      type: 'object',
      properties: {
        op:           { type: 'string', enum: ['create', 'customize', 'export', 'remote', 'collab'], description: 'Which presentation action to run.' },
        project_path: { type: 'string', description: 'Project dir (op:create; resolves relative design_path elsewhere).' },
        name:         { type: 'string', description: 'op:create — presentation name.' },
        pages:        { type: 'array', description: 'op:create — [{id?, label, notes?}] slide specs.', items: { type: 'object' } },
        transition:   { type: 'string', enum: ['none', 'fade', 'slide-left', 'slide-right', 'slide-up', 'slide-down', 'zoom-in', 'zoom-out', 'flip-h', 'flip-v', 'cube-left', 'cube-right', 'reveal', 'wipe-left', 'wipe-right', 'dissolve', 'morph'], default: 'fade', description: 'op:create — slide transition.' },
        auto_advance: { type: 'number', description: 'op:create/export — auto-advance delay ms (0 = manual).' },
        width:        { type: 'number', default: 1920, description: 'op:create — slide width.' },
        height:       { type: 'number', default: 1080, description: 'op:create — slide height.' },
        theme:        { type: 'string', enum: ['dark', 'light'], default: 'dark', description: 'op:create/export — presenter theme.' },
        design_path:  { type: 'string', description: 'op:customize/export/remote/collab — the .design.yaml.' },
        changes:      { type: 'object', description: 'op:customize — presentation settings to merge (theme, transition, auto_advance, show_controls, aspect_ratio), plus width/height to re-shape every slide.', properties: {} },
        dry_run:      { type: 'boolean', description: 'op:customize — return the diff without writing.' },
        output_path:  { type: 'string', description: 'op:export — output .html path (auto if omitted).' },
        port:         { type: 'number', description: 'op:remote (default 3737) / op:collab (default 3738) — server port.' },
      },
      required: ['op'],
    },
  },
  {
    name: 'animation',
    description: 'Motion authoring + export — the After-Effects layer of Folio. Pick `op`:\n• presets — the menu: every preset (entrances/exits/loops), easing curve, animatable channel and anchor, each with a one-line note. Read-only, no design needed.\n• sequence — build a WHOLE SCENE in one call (req: design_path, steps:[{preset, layer_ids?, at?, duration?, stagger_ms?, easing?, distance?}]). Steps run in order; a step without `at` starts when the previous one ends, so [{preset:"rise", layer_ids:[title]}, {preset:"rise", layer_ids:[a,b,c], stagger_ms:90}, {preset:"fade_out", at:4000}] is a complete enter–hold–exit story. Entrances, exits and holds on the SAME layer fold into one track; a loop needs its own layer.\n• track — write a layer\'s raw keyframe track for full control (req: design_path, layer_id|layer_ids, keyframes:[{t:ms, x?, y?, opacity?, scale?, scale_x?, scale_y?, rotation?, skew_x?, skew_y?, blur?, draw?, "fill.color"?, easing?, hold?}], opt: playback:{duration, loop, iterations, direction, easing, delay, anchor, origin}, stagger_ms). x/y are OFFSETS from where the layer sits (origin:"offset" default). `easing` on a keyframe shapes the segment leaving it; `hold:true` freezes until the next frame. `draw` 0→1 reveals a stroke along its length. `anchor` is the pivot (center | top | bottom | left | right | corners).\n• motion — one preset on some layers (req: design_path, preset; opt: page_id, layer_ids, stagger_ms, duration, easing, distance). Same as a one-step sequence.\n• keyframe — add/replace ONE keyframe on a layer (req: design_path, layer_id, keyframe:{t, …}).\n• frame — render the design AS IT LOOKS AT TIME t as a PNG attachment + the resolved geometry of every animated layer (req: design_path; opt: t ms, page_id, scale, output_path). The way to check a pose without watching it play.\n• timeline — the scene as a Gantt: every track\'s start/end, kind (loop|one-shot), channels, plus an ASCII view and scene_ms (req: design_path; opt: page_id).\n• clear — remove motion from some or all layers on a page (req: design_path; opt: layer_ids, page_id).\n• export — write a motion file (req: design_path, type). type:"svg"/"html" are the DEFAULT: real animated files written in-process, vector-sharp, usually a few KB, every channel plays. type:"gif" is a raster flipbook encoded in-process (no ffmpeg) for feeds that refuse SVG — skew and draw hold at rest there. type:"mp4"/"webm" need Puppeteer + ffmpeg on the host. all_pages:true writes one file per carousel page.\nEasing vocabulary: linear, ease, ease-in/out/in-out, ease-{in,out,in-out}-{quad,cubic,quart,expo,circ,back,elastic,bounce}, snap, smooth, pop, spring, bounce, hold, cubic-bezier(…), steps(n).',
    inputSchema: {
      type: 'object',
      properties: {
        op:           { type: 'string', enum: ['presets', 'sequence', 'track', 'motion', 'motion_path', 'keyframe', 'frame', 'preview', 'timeline', 'clear', 'export'], description: 'Which animation action to run.' },
        design_path:  { type: 'string', description: 'Path to .design.yaml (every op except presets).' },
        page_id:      { type: 'string', description: 'Which page of a carousel/deck to act on (default: first).' },
        project_path: { type: 'string', description: 'Project dir — enables relative design_path.' },
        path:         { type: 'string', description: 'op:motion_path — the SVG path the layer travels, as a `d` string. It OFFSETS the layer from where it already sits, so it normally starts at "M 0 0" (e.g. "M 0 0 Q 200 -120 400 0" arcs right and back down). M L H V C S Q T Z, absolute or relative; elliptical arcs (A) are refused because the exporter would have to approximate them and the frames would then disagree with the browser.' },
        auto_rotate:  { type: 'boolean', description: 'op:motion_path — turn the layer to face along the curve as it travels.' },
        clear:        { type: 'boolean', description: 'op:motion_path — remove the path from the named layers instead of setting one.' },
        steps:        { type: 'array', items: { type: 'object', properties: {} }, description: 'op:sequence — ordered steps [{preset, layer_ids?, at?, duration?, stagger_ms?, easing?, distance?}]. Omit `at` to start when the previous step ends; omit layer_ids to target the whole page.' },
        layer_id:     { type: 'string', description: 'op:keyframe/track — target layer id.' },
        layer_ids:    { type: 'array', items: { type: 'string' }, description: 'op:motion/track/clear — layers to act on, IN THE ORDER they should fire. Omit to target every layer on the page (a LOCKED group counts as one unit).' },
        preset:       { type: 'string', description: 'op:motion — preset name. Entrances: fade_in, rise, settle, scale_in, sweep_in, pop, drop, blur_in, draw_on, spin_in, flip_in, grow_up, whip. Exits: fade_out, sink, shrink_out, blur_out, sweep_out, pop_out. Loops: pulse, float, spin, drift, breathe, wobble, sway, heartbeat, flicker.' },
        keyframes:    { type: 'array', items: { type: 'object', properties: {} }, description: 'op:track — the whole track, ≥2 frames: [{t:0, opacity:0, y:24, easing:"ease-out-expo"}, {t:600, opacity:1, y:0}].' },
        playback:     { type: 'object', description: 'op:track — {duration?, loop?, iterations?, direction?:"normal"|"alternate", easing?, delay?, anchor?, origin?:"offset"|"first"}.', properties: {} },
        keyframe:     { type: 'object', description: 'op:keyframe — {t:ms, x?, y?, opacity?, scale?, rotation?, blur?, draw?, easing?, hold?}.', properties: {} },
        stagger_ms:   { type: 'number', description: 'op:motion/track — delay between consecutive layers, ms. 60–120 reads well for a list.' },
        easing:       { type: 'string', description: 'op:motion — curve name (see the vocabulary above) or cubic-bezier(...). Per-preset default if omitted.' },
        distance:     { type: 'number', description: 'op:motion — travel distance in px for travelling presets. Per-preset default if omitted.' },
        duration:     { type: 'number', description: 'op:motion — run length ms. op:export — total clip length ms (default: the scene length).' },
        t:            { type: 'number', description: 'op:frame — time to render, ms from scene start (default 0).' },
        frames:       { type: 'number', description: 'op:preview — how many poses to sample across the scene (2-24, default 6).' },
        cell:         { type: 'number', description: 'op:preview — longest edge of each filmstrip cell in px (80-480, default 260).' },
        strip_only:   { type: 'boolean', description: 'op:preview — return only the inline filmstrip, skipping the .preview.gif file.' },
        scale:        { type: 'number', description: 'op:frame — raster scale 0.25–2 (default 1).' },
        type:         { type: 'string', enum: ['svg', 'html', 'gif', 'mp4', 'webm'], description: 'op:export — output format. svg = self-contained animated SVG. html = the same in a shareable page honoring prefers-reduced-motion. gif = in-process raster flipbook. mp4/webm need Puppeteer + ffmpeg.' },
        all_pages:    { type: 'boolean', description: 'op:export — one animated file per carousel page (`<name>-p1.gif`, …).' },
        output_path:  { type: 'string', description: 'op:export/frame — output file path (auto if omitted; frame returns inline when omitted).' },
        fps:          { type: 'number', description: 'op:export — frames per second (default 12 gif, 30 mp4/webm).' },
      },
      required: ['op'],
    },
  },
];
