// §7 Tier 3 — Output + Advanced (8 tools): inspect/preview, export, editor link,
// and the four advanced subsystems (templates, reports, presentations, animation)
// each folded into ONE multiplexed tool with an `op` discriminator. Capability is
// identical to the old per-tool surface — only the tool count shrank.
import type { ToolDefinition } from '../types';

export const TIER3_TOOLS: ToolDefinition[] = [
  {
    name: 'render_preview',
    description: 'Render the design to a PNG and return it INLINE as an image so you can SEE what you produced (no file written). Use it to visually verify a composition or confirm a fix — pair with diagnose_design. Foreground charts/KPIs that need a browser still only appear in the editor; everything else (shapes, patterns, text, fills) rasterizes here. COST: the preview is downscaled to a 960px longest edge by default (~a quarter of the image tokens of a full-size render) — enough to judge layout, overlap, hierarchy and colour. The response quotes `est_image_tokens` so you can budget a verification loop; pass full:true (or an explicit scale) only when you need to read fine copy.',
    inputSchema: {
      type: 'object',
      properties: {
        design_path:  { type: 'string', description: 'Path to .design.yaml' },
        project_path: { type: 'string', description: 'Project dir — enables relative design_path' },
        page_id:      { type: 'string', description: 'Carousel: preview one page (omit = first page)' },
        scale:        { type: 'number', description: 'Raster scale 0.5–2 — setting it opts out of the cheap default and renders at that scale' },
        max_edge:     { type: 'number', description: 'Longest edge in px for the cheap default (default 960)', default: 960 },
        full:         { type: 'boolean', description: 'Full canvas resolution — costs ~4× the tokens of the default', default: false },
        changed_only: { type: 'boolean', description: 'MULTI-PAGE RE-CHECK: render only the pages whose rendered output actually moved since the last preview, in ONE call. Without it, verifying an 8-page deck after a one-page edit costs 8 calls and 8 images. Pages that render byte-identically are named and skipped, not charged for. The first call on a design has no baseline, so every page counts as a first look; the next one skips whatever has not moved. Ignored with page_id or on a single-page design.', default: false },
      },
      required: ['design_path'],
    },
  },
  {
    name: 'diagnose_design',
    description: 'Built-in troubleshooter — scans a design for problems the model is blind to and returns structured findings with fixes: off-canvas layers, collisions/overlap pile-ups, near-miss MISALIGNMENT (edges off by a few px), tiny text, low-contrast/invisible text, missing background, plus quality critique (weak hierarchy, accent sprawl, crowded margins). For a design shaped like an IDENTITY MARK (single page, roughly square, <=1200px, few layers) it also returns `mark`: optical_center (centroid-of-ink vs bounding-box centre — box-centring is what makes a play triangle look pushed left), scale_survival (rendered at 16/24/32/64/128/512px, reporting where detail collapses), contrast against white/black/mid-grey, and a clearspace rule derived from the mark\'s own stroke width. It MEASURES a mark you drew; it never generates one. See get_engine_guide(section:"marks"). Run it after composing and before seal_design; fix the errors/warnings, then render_preview to confirm. SELF-HEAL: pass heal:true and it becomes a LOOP — diagnose, fix, re-diagnose, repeat until clean or until a pass changes nothing (progress is the stop condition, not a round count). It fixes SPATIAL CORRECTNESS and LEGIBILITY only: a preset whose content leaves the canvas is re-laid out from its stored spec at the size it actually has, stranded layers come back on-canvas, sub-14px text is raised, a missing ground is filled, invisible text is re-lit, positionless layers are flowed. It deliberately does NOT touch palette, hierarchy, composition or copy — those come back as `for_you_to_judge`, because a loop that re-made aesthetic decisions would converge every design on one look. The reply separates what it fixed, what it COULD have fixed but could not (`could_not_fix` — usually too much content for the canvas), and what is yours to decide. Add dry_run:true to see the plan first.',
    inputSchema: {
      type: 'object',
      properties: {
        design_path:  { type: 'string', description: 'Path to .design.yaml' },
        project_path: { type: 'string', description: 'Project dir — enables relative design_path' },
        page_id:      { type: 'string', description: 'Carousel: diagnose one page (omit = all pages)' },
        heal:         { type: 'boolean', description: 'Run the self-heal LOOP instead of just reporting: fix what is mechanically fixable, re-diagnose, repeat.', default: false },
        max_rounds:   { type: 'number', description: 'heal only — cap the loop (default 3, max 5). It stops early as soon as a pass fixes nothing.', default: 3 },
        dry_run:      { type: 'boolean', description: 'heal only — report the fixes it would apply without writing.' },
      },
      required: ['design_path'],
    },
  },
  {
    name: 'export_design',
    description: 'Export a design to SVG, PNG, PDF, HTML or PPTX (all produce real files). A carousel exports one file per page (`<name>-p1.svg`, `-p2.svg`, …); output_paths lists them. pdf is a true VECTOR PDF: text is embedded as real, selectable/copy-paste glyphs that stay crisp at any zoom, drawn over a high-DPI raster for backgrounds/gradients/effects, with clickable links — no Puppeteer/Chromium needed. pptx is a PowerPoint deck — one full-bleed image slide per page (pixel-faithful; opens in PowerPoint/Keynote/Slides as an editable container). For an INTERACTIVE report use report(op:export); for a presentation HTML/video use presentation(op:export) / animation(op:export).',
    inputSchema: {
      type: 'object',
      properties: {
        design_path:  { type: 'string', description: 'Path to .design.yaml' },
        format:       { type: 'string', enum: ['svg', 'html', 'pdf', 'png', 'pptx'] },
        output_path:  { type: 'string', description: 'Output path (auto-derived if omitted)' },
        project_path: { type: 'string', description: 'Project dir — enables relative design_path' },
        scale:        { type: 'number', description: 'Scale factor 1–3', default: 2 },
        force:        { type: 'boolean', description: 'Re-render even if this exact export was already produced. A repeat with the same design, format, scale and destination is answered from disk instead of rendered again (single-file formats), so a retry after a timeout does not redo finished work. An export killed mid-render records nothing and is always redone.', default: false },
      },
      required: ['design_path', 'format'],
    },
  },
  {
    name: 'open_in_editor',
    description: 'Return a clickable, token-embedded URL that opens a design in the Folio editor (live-refreshes as later tools edit the file). NOTE: create_design/append_page/seal_design/export_design already return this as open_url — only call this to re-open, focus a page, or open the editor home.',
    inputSchema: {
      type: 'object',
      properties: {
        design_path:  { type: 'string',  description: 'Path to .design.yaml — omit to open the editor at its home page' },
        project_path: { type: 'string',  description: 'Project dir for resolving relative design_path' },
        editor_url:   { type: 'string',  description: 'Override editor base URL (default: $FOLIO_EDITOR_URL or http://localhost:4173)' },
        page:         { type: 'number',  description: 'Page index to focus (1-based)' },
      },
      required: [],
    },
  },
  {
    name: 'templates',
    description: 'Built-in template catalog + reusable components — pick `op`:\n• list — browse the 432 built-in catalog templates (same as the editor Catalog); slim metadata {id,name,type,tags,width,height,slots,themeRef}; filter search/tag/limit. Feed a returned id straight to op:slots / op:inject.\n• slots — list injectable slots (paths/types/hints) of a template (req: template_path = a real .template.yaml path OR a built-in catalog id).\n• inject — fill slot values → a new .design.yaml (req: template_path, slots map; a built-in writes into the projects dir).\n• export — turn a sealed design into a reusable .template.yaml skeleton with named slots (req: design_path).\n• save_component — extract layers into a REUSABLE .component.yaml + replace them with an instance (req: design_path, layer_ids, component_name, project_path). Every text layer becomes a named {{slot}} with its current copy as the default, so the next instance can carry different content — that is what makes it a component rather than a copy-paste. Pass auto_slots:false to freeze the copy instead.\n• components — what this project can compose FROM: each saved component with its id, slots, variants and layer count (req: project_path). Without this the component store is write-only — place one with {type:\"component\", ref, pos, slots:{…}}.\n• batch — generate N designs from one template + an array of slot objects (req: project_path, template_id = a built-in catalog id OR a project .template.yaml id OR a design name to clone, slots_array).',
    inputSchema: {
      type: 'object',
      properties: {
        op:             { type: 'string', enum: ['list', 'slots', 'inject', 'export', 'save_component', 'components', 'batch'], description: 'Which template/component action to run.' },
        search:         { type: 'string', description: 'op:list — free-text match over id/name/tags.' },
        tag:            { type: 'string', description: 'op:list — exact tag filter (e.g. "poster", "resume").' },
        limit:          { type: 'number', description: 'op:list — max results (default 60, max 300).' },
        template_path:  { type: 'string', description: 'op:slots/inject — a real .template.yaml path OR a built-in catalog id / filename (see op:list).' },
        slots:          { type: 'object', description: 'op:inject — map of slot_id → value.', properties: {} },
        output_path:    { type: 'string', description: 'op:inject/export — output path (auto if omitted).' },
        design_path:    { type: 'string', description: 'op:export/save_component — source .design.yaml.' },
        project_path:   { type: 'string', description: 'Project dir (op:export/save_component/components/batch).' },
        auto_slots:     { type: 'boolean', description: 'op:save_component — turn each text layer into a named slot (default true). false freezes the copy.', default: true },
        layer_ids:      { type: 'array', description: 'op:save_component — layer IDs to extract.', items: { type: 'string' } },
        component_name: { type: 'string', description: 'op:save_component — name for the new component.' },
        template_id:    { type: 'string', description: 'op:batch — a built-in catalog id, a project .template.yaml id, or a design name in the project to clone.' },
        slots_array:    { type: 'array', description: 'op:batch — one slot object per design.', items: { type: 'object' } },
      },
      required: ['op'],
    },
  },
  {
    name: 'report',
    description: 'Interactive data-report subsystem (type:report designs) — pick `op`:\n• generate — scaffold a report with pages/nav/optional data; layout:"flow" = responsive 12-col interactive dashboard (set accent + font_heading/font_body) (req: project_path, name, pages).\n• customize — RESTYLE a report in place instead of regenerating it (req: design_path, changes). Merges into the report settings — layout, nav, accent, max_width, font_heading/font_body — and {width,height} re-shapes the canvas, re-laying out every preset from its stored spec rather than stretching it. Regenerating would discard everything composed since; this keeps it. Objects merge key by key, arrays replace, null deletes; dry_run:true shows the diff.\n• bind_data — attach/update inline datasets for $data.* / $agg.* expressions (req: design_path, datasets:[{id,rows[]}]).\n• validate — lint cross-refs (charts/tables/filters resolve to real datasets+fields, buttons open real modals) BEFORE export; returns {ok,errors,warnings} (req: design_path).\n• export — assemble into a self-contained interactive HTML; returns view_url (the real result to give the user) + edit_url (req: design_path).\n• formula — store state/data context for =expr bindings on a design (req: design_path).\n• debug — evaluate one =formula against a context and return the typed result (req: formula).',
    inputSchema: {
      type: 'object',
      properties: {
        op:           { type: 'string', enum: ['generate', 'customize', 'bind_data', 'validate', 'export', 'formula', 'debug'], description: 'Which report action to run.' },
        project_path: { type: 'string', description: 'Project dir (op:generate; resolves relative design_path elsewhere).' },
        name:         { type: 'string', description: 'op:generate — report name.' },
        layout:       { type: 'string', enum: ['paged', 'scroll', 'tabs', 'sidebar', 'flow'], default: 'paged', description: 'op:generate — flow = responsive 12-col interactive grid.' },
        nav_type:     { type: 'string', enum: ['sidebar', 'topbar', 'tabs', 'dots'], default: 'sidebar', description: 'op:generate — navigation style.' },
        pages:        { type: 'array', description: 'op:generate — [{id?, label}] page specs. OPTIONAL: omit for a flow/scroll report, which is one continuous scrolling document and gets a single page automatically.', items: { type: 'object' } },
        width:        { type: 'number', default: 1080, description: 'op:generate — canvas width.' },
        height:       { type: 'number', default: 1080, description: 'op:generate — canvas height.' },
        data_sources: { type: 'array', description: 'op:generate — optional inline/json/csv data sources.', items: { type: 'object' } },
        max_width:    { type: 'number', description: 'op:generate (flow) — centered container max width px (default 1200).' },
        accent:       { type: 'string', description: 'op:generate (flow) — accent color seeding charts/links/active states.' },
        font_heading: { type: 'string', description: 'op:generate (flow) — heading font family (Google font name).' },
        font_body:    { type: 'string', description: 'op:generate (flow) — body font family (Google font name).' },
        design_path:  { type: 'string', description: 'op:customize/bind_data/validate/export/formula/debug — the .design.yaml.' },
        changes:      { type: 'object', description: 'op:customize — report settings to merge (layout, navigation, accent, max_width, font_heading, font_body), plus width/height to re-shape the canvas. Only what you want different.', properties: {} },
        dry_run:      { type: 'boolean', description: 'op:customize — return the diff without writing.' },
        datasets:     { type: 'array', description: 'op:bind_data — [{id, rows[]}].', items: { type: 'object' } },
        output_path:  { type: 'string', description: 'op:export — output .html path (auto if omitted).' },
        theme:        { type: 'string', enum: ['light', 'dark'], default: 'dark', description: 'op:export — report theme.' },
        state:        { type: 'object', description: 'op:formula/debug — state variables.', properties: {} },
        data:         { type: 'object', description: 'op:formula/debug — data variables.', properties: {} },
        formula:      { type: 'string', description: 'op:debug — formula string starting with =.' },
      },
      required: ['op'],
    },
  },
  {
    name: 'presentation',
    description: 'Slide presentations + live presenting/collab — pick `op`:\n• create — scaffold a presentation design (1920×1080) with slides + transition (req: project_path, name, pages:[{label,notes?}]).\n• customize — RESTYLE or RE-SHAPE a deck in place instead of recreating it (req: design_path, changes). Merges into the presentation settings — theme, transition, auto_advance, controls, aspect_ratio — and {width,height} re-shapes every slide: presets re-EXPAND into the new page box from their stored spec (a real re-layout, not a stretch), hand-placed layers scale and centre. This is how a 1920×1080 deck becomes a 1080×1350 carousel without rebuilding it. dry_run:true shows the diff.\n• export — assemble a presentation/carousel/motion into a self-contained HTML presenter with transitions + keyboard nav (req: design_path).\n• remote — generate a remote-clicker setup: client JS + curl commands to drive slides over HTTP (opt: port, design_path).\n• collab — generate a collaborative-editing SSE file-watch server for multi-user sync (req: design_path).',
    inputSchema: {
      type: 'object',
      properties: {
        op:           { type: 'string', enum: ['create', 'customize', 'export', 'remote', 'collab'], description: 'Which presentation action to run.' },
        project_path: { type: 'string', description: 'Project dir (op:create; resolves relative design_path elsewhere).' },
        name:         { type: 'string', description: 'op:create — presentation name.' },
        pages:        { type: 'array', description: 'op:create — [{id?, label, notes?}] slide specs.', items: { type: 'object' } },
        transition:   { type: 'string', enum: ['none', 'fade', 'slide-left', 'slide-right', 'slide-up', 'slide-down', 'zoom-in', 'zoom-out', 'flip-h', 'flip-v', 'cube-left', 'cube-right', 'reveal', 'wipe-left', 'wipe-right', 'dissolve', 'morph'], default: 'fade', description: 'op:create — slide transition.' },
        auto_advance: { type: 'number', description: 'op:create/export — auto-advance delay ms (0 = manual).' },
        width:        { type: 'number', default: 1920, description: 'op:create — slide width.' },
        height:       { type: 'number', default: 1080, description: 'op:create — slide height.' },
        theme:        { type: 'string', enum: ['dark', 'light'], default: 'dark', description: 'op:create/export — presenter theme.' },
        design_path:  { type: 'string', description: 'op:customize/export/remote/collab — the .design.yaml.' },
        changes:      { type: 'object', description: 'op:customize — presentation settings to merge (theme, transition, auto_advance, show_controls, aspect_ratio), plus width/height to re-shape every slide.', properties: {} },
        dry_run:      { type: 'boolean', description: 'op:customize — return the diff without writing.' },
        output_path:  { type: 'string', description: 'op:export — output .html path (auto if omitted).' },
        port:         { type: 'number', description: 'op:remote (default 3737) / op:collab (default 3738) — server port.' },
      },
      required: ['op'],
    },
  },
  {
    name: 'animation',
    description: 'Motion authoring + export — the After-Effects layer of Folio. Pick `op`:\n• storyboard — ONE continuous scene told in shots, the way a 30 s motion piece is built: no page transitions, the objects carry the story (req: design_path, shots:[{id?, at, states:{<layer id>: {x?, y?, dx?, dy?, scale?, rotation?, opacity?, blur?, "fill.color"?, enter?:<entrance preset>, exit?:<exit preset>, loop?:<loop preset>, loop_ms?, hidden?, duration?, delay?, easing?} | "hidden" | "show" | "still" | "<preset>"}, duration?, easing?, stagger_ms?, order?, hold?}], opt: length_ms, hold_ms, page_id). Write WHERE each object is in each shot — a loop is how a layer rests there (whole passes until its next change; "still" stops it) — x/y place the top-left of what the layer draws, after its scale; layers not named keep their state; the design as authored is the state before shot 1. The engine writes the keyframes that carry each layer from state to state (it stays where it lands), in/out points for what enters and leaves, and each shot id as a marker. Replies with each layer\'s landings and a time-aware lint: overlaps at rest, text off the frame, text a shot lands under an opaque layer, idle stretches, too many things moving at once, shots too short to read.\n• markers — named points on the scene clock (req: design_path; markers:{hook:0, problem:4000, cta:"problem+6000"}; null removes one; clear:true). Every composition time — storyboard at, span in/out, sequence at, camera t, precomp start — takes ms, a marker, a layer point ("title.in", "title.out", "card.start", "card.end") or either ± ms.\n• span — a layer\'s in and out points (req: design_path, layer_id|layer_ids, in? out? — times or names; clear:true): it exists only between them, in every export, op:frame and the cost of a raster frame.\n• retime — a ripple edit on the scene clock (req: design_path, at, shift_ms): shift_ms>0 opens that many ms at `at` — a longer shot, a longer rest — and shift_ms<0 closes the span after it. Every keyframe, in/out point, path, precomp start, marker and the scene length at or after `at` moves together, and on a one-scene piece its sounds and captions too; a bed playing across it plays on to the new end. What was moving at `at` runs longer (the reply names it), so put `at` in a rest. Closing is refused while anything starts or lands inside the span. The way to act on a lint note that a shot is short of reading time.\n• precomp — a group with its OWN clock (req: design_path, layer_id; opt: layer_ids to wrap loose siblings into a new group named layer_id, start, speed, loop_ms, clear, duplicate:{id, start?, dx?, dy?}): its children are authored from local 0 and play from start, at speed, repeating every loop_ms. duplicate places a second instance of the same sub-sequence.\n• link — follow-through: a layer plays another layer\'s motion lag ms later, its travel ×factor (req: design_path, layer_id|layer_ids, to; opt: channels [x,y,rotation,scale,…], lag default 100, factor default 1, stagger_ms adds lag per follower, clear). Rides on a <id>_link wrapper, so the layer\'s own track keeps playing; live — change the target and the followers follow.\n• lint — the storyboard\'s time-aware checks on any page, writing nothing (req: design_path; markers act as shots).\n• presets — the menu: every preset (entrances/exits/loops), easing curve, animatable channel and anchor, each with a one-line note. Read-only, no design needed.\n• sequence — build a WHOLE SCENE in one call (req: design_path, steps:[{preset, layer_ids?, at?, duration?, stagger_ms?, easing?, distance?}]). Steps run in order; a step without `at` starts when the previous one ends, so [{preset:"rise", layer_ids:[title]}, {preset:"rise", layer_ids:[a,b,c], stagger_ms:90}, {preset:"fade_out", at:4000}] is a complete enter–hold–exit story. Entrances, exits and holds on the SAME layer fold into one track; a loop needs its own layer.\n• text — After Effects\' text animator in ONE call (req: design_path, layer_id, preset|keyframes): splits the text layer into by:"char"|"word"|"line" units placed by measured font advances (a wrapped paragraph along its drawn lines), then staggers them with stagger_ms + order. mask:true holds a clip still over each unit so it rises from under an edge. Works inside page groups.\n• wiggle — After Effects\' wiggle (req: design_path, layer_id|layer_ids, amplitude:{x?,y?,rotation?,scale?}; frequency? per second, duration? loop ms, seed?): wraps the layer in an <id>_wiggle group that loops seeded noise, so whatever the layer already does keeps playing underneath. Same wiggle every export; seed re-rolls it.\n• camera — a 2D camera over the page (req: design_path, shots:[{t, target:"all"|"world"|id|[ids]|{x,y,width,height}, padding?, easing?, hold?, rotation?}]): moves the content under a __camera group and frames each shot\'s target to fill the canvas — push in on a stat, pull back, pan. t takes a marker ("problem"). world:{x,y,width,height} | "auto" lays the page out larger than the canvas — park sections side by side and let the camera travel between them instead of cutting pages; world alone (no shots) declares it BEFORE the layout, so content past the canvas edge is not pulled back. The page ground stays still; exclude:[ids] holds other layers still. Call again to re-frame.\n• morph — one path becomes another shape (req: design_path, layer_id, to:"<d>" | to_layer:"<path id>"; duration?, delay?, easing?, keep_target?): resamples both outlines to the same points and writes a morph 0→1 track merged onto the layer\'s motion; the target layer is hidden. Elliptical arcs (A) are refused.\n• track — write a layer\'s raw keyframe track for full control; it REPLACES the motion the layer had, so put every channel in it (req: design_path, layer_id|layer_ids, keyframes:[{t:ms, x?, y?, opacity?, scale?, scale_x?, scale_y?, rotation?, skew_x?, skew_y?, blur?, draw?, "fill.color"?, easing?, hold?}], opt: playback:{duration, loop, iterations, direction, easing, delay, anchor, origin}, stagger_ms). x/y are OFFSETS from where the layer sits (origin:"offset" default). `easing` on a keyframe shapes the segment leaving it; `hold:true` freezes until the next frame. `draw` 0→1 reveals a stroke along its length. `anchor` is the pivot (center | top | bottom | left | right | corners).\n• motion — one preset on some layers (req: design_path, preset; opt: page_id, layer_ids, stagger_ms, duration, easing, distance). Same as a one-step sequence.\n• keyframe — add/replace ONE keyframe on a layer (req: design_path, layer_id, keyframe:{t, …}).\n• frame — render the design AS IT LOOKS AT TIME t as a PNG attachment + the resolved geometry of every animated layer on screen that is off its authored pose (poses), with the ones resting where they were authored named in at_rest (req: design_path; opt: t ms, page_id, scale, output_path). The way to check a pose without watching it play. scenes:true renders any moment of the whole multi-scene piece (t from its start), mid-transition included.\n• timeline — the scene as a Gantt: every track\'s start/end, kind (loop|one-shot), channels, plus an ASCII view and scene_ms (req: design_path; opt: page_id). scenes:true shows every scene\'s start, length and transition instead.\n• scene — how a PAGE plays as one scene of a multi-scene piece (req: design_path, page_id; opt: transition:{type, duration?, easing?} = how it ENTERS — fade, slide-left/right/up/down, zoom-in/out, wipe-left/right, reveal, flip-h/v, cube-left/right, dissolve, morph, none; length_ms = exact time on screen, 0 = its motion + the export hold). Answers with the whole piece\'s plan.\n• audio — the SOUND of a video (mp4/webm; a GIF has none). Find a sound with manage_design(op:asset_search, what:"music"|"sound") + op:asset_fetch, or store your own with op:asset_add. src:"lib/audio/…"|"assets/audio/…" (+ volume 0–1, fade_in, fade_out, start_ms, offset_ms, duration, loop) adds music under the WHOLE piece; with page_id it is a cue that starts with that scene (start_ms = ms after the scene\'s first frame). audio_id + fields changes one; remove:true takes one (or all) out; no src lists the soundtrack as it will mix — each clip\'s from/to on the piece, a lane per clip in ascii, and notes when music is cut off with no fade or runs out early. The scenes set the piece\'s length; sound is cut at its end.\n• beats — MEASURE the music (req: design_path; opt: audio_id, default the first track): bpm, beat_ms, bar_ms, confidence + pulse (steady | weak | none), every beat and the sharpest onsets as ms on the PIECE timeline, an ascii grid under the scene cuts, and scenes_on_beat — for each scene the length_ms that ends it on its nearest beat without cutting its motion or reading time (longer_for names which pushed it to a later beat; each counting the ones before it). Writes nothing: apply a length with op:scene, or keep a cut where the story wants it.\n• captions — the WORDS on screen (req: design_path). page_id + lines:[{text, at?, duration?}] sets that scene\'s captions from its first frame (untimed lines share the scene by word count); cues:[{text, from_ms, to_ms}] sets captions on the whole piece; style:{position:"bottom"|"top", font_family, font_size, font_weight, color, background|"none", background_opacity, max_width 0–1, margin} merges; clear:true removes (a scene\'s with page_id); format:"srt"|"vtt" also writes a subtitle file. Every reply lists the captions as they will show, with notes when one needs more than ~17 characters a second, flashes under 1s, or overlaps another. Burned into gif/mp4/webm, op:frame and Play all (op:export captions:false leaves them out); not in svg/html.\n• clear — remove motion from some or all layers on a page (req: design_path; opt: layer_ids, page_id).\n• export — write a motion file (req: design_path, type). type:"svg"/"html" are the DEFAULT: real animated files written in-process, vector-sharp, usually a few KB, every channel plays. type:"gif" is a raster flipbook for feeds that refuse SVG, encoded in-process AS IT RENDERS — a 30s scene keeps its fps, identical frames merge. type:"mp4" (H.264) / "webm" (VP9) pipe the same frames into ffmpeg. Every channel plays in every format. Raster clips run up to 60s. all_pages:true writes one file per carousel page. scenes:true plays EVERY page in order as ONE gif/mp4/webm — each page a scene with its own timeline (author each with page_id), entering with its op:scene transition; hold_ms is the rest after each scene\'s motion (default 1500, a page\'s length_ms wins). The reply lists the scenes and warns when one is too short to read. A raster clip over 150 frames renders as a BACKGROUND JOB: the reply carries a job_id at once (background:false waits for the file instead).\n• export_status — where a background export has got to (req: job_id): frames done, percent, eta_ms, then the receipt with the file. Exporting the same file again while it renders joins that job instead of starting over.\nEasing vocabulary: linear, ease, ease-in/out/in-out, ease-{in,out,in-out}-{quad,cubic,quart,expo,circ,back,elastic,bounce}, snap, smooth, pop, spring, bounce, hold, cubic-bezier(…), steps(n).',
    inputSchema: {
      type: 'object',
      properties: {
        op:           { type: 'string', enum: ['presets', 'storyboard', 'sequence', 'track', 'motion', 'motion_path', 'text', 'wiggle', 'camera', 'morph', 'precomp', 'link', 'markers', 'span', 'retime', 'keyframe', 'frame', 'preview', 'timeline', 'lint', 'clear', 'export', 'export_status', 'scene', 'audio', 'beats', 'captions'], description: 'Which animation action to run.' },
        design_path:  { type: 'string', description: 'Path to .design.yaml (every op except presets).' },
        page_id:      { type: 'string', description: 'Which page of a carousel/deck to act on (default: first).' },
        project_path: { type: 'string', description: 'Project dir — enables relative design_path.' },
        path:         { type: 'string', description: 'op:motion_path — the SVG path the layer travels, as a `d` string. It OFFSETS the layer from where it already sits, so it normally starts at "M 0 0" (e.g. "M 0 0 Q 200 -120 400 0" arcs right and back down). M L H V C S Q T Z, absolute or relative; elliptical arcs (A) are refused because the exporter would have to approximate them and the frames would then disagree with the browser.' },
        auto_rotate:  { type: 'boolean', description: 'op:motion_path — turn the layer to face along the curve as it travels.' },
        clear:        { type: 'boolean', description: 'op:motion_path — remove the path from the named layers instead of setting one. op:captions — remove captions (with page_id: that scene\'s only). op:markers — remove every marker first. op:span — remove the in/out points. op:precomp — remove the clock. op:link — unwrap the followers.' },
        cues:         { type: 'array', items: { type: 'object', properties: {} }, description: 'op:captions — captions on the whole piece, replacing the ones there: [{text, from_ms, to_ms}] in ms from the start of the piece.' },
        lines:        { type: 'array', items: { type: 'object', properties: {} }, description: 'op:captions with page_id — that scene\'s captions, replacing its own: [{text, at?, duration?}] (or plain strings), ms from the scene\'s first frame. Lines without times share the scene by word count.' },
        style:        { type: 'object', properties: {}, description: 'op:captions — how captions look, merged into the current style: {position:"bottom"|"top", font_family, font_size px, font_weight, color, background ("none" = no box), background_opacity, max_width (fraction of the canvas width), margin px}.' },
        format:       { type: 'string', enum: ['srt', 'vtt'], description: 'op:captions — also write the captions as a subtitle file (exports/<name>.srt|.vtt, or output_path).' },
        captions:     { type: 'boolean', description: 'op:export gif/mp4/webm — false leaves the design\'s captions out of the frames (default: burned in).' },
        steps:        { type: 'array', items: { type: 'object', properties: {} }, description: 'op:sequence — ordered steps [{preset, layer_ids?, at?, duration?, stagger_ms?, easing?, distance?}]. Omit `at` to start when the previous step ends; omit layer_ids to target the whole page.' },
        layer_id:     { type: 'string', description: 'op:keyframe/track/span/link — target layer id. op:precomp — the precomp group (with layer_ids: the id of the new group).' },
        layer_ids:    { type: 'array', items: { type: 'string' }, description: 'op:motion/track/clear — layers to act on, IN THE ORDER they should fire. Omit to target every layer on the page (a LOCKED group counts as one unit).' },
        preset:       { type: 'string', description: 'op:motion — preset name. Entrances: fade_in, rise, settle, scale_in, sweep_in, pop, drop, blur_in, draw_on, spin_in, flip_in, grow_up, whip, wipe_in, track_in, count_up. Exits: fade_out, sink, shrink_out, blur_out, sweep_out, pop_out, wipe_out. Loops: pulse, float, spin, drift, breathe, wobble, sway, heartbeat, flicker.' },
        keyframes:    { type: 'array', items: { type: 'object', properties: {} }, description: 'op:track — the whole track, ≥2 frames: [{t:0, opacity:0, y:24, easing:"ease-out-expo"}, {t:600, opacity:1, y:0}].' },
        playback:     { type: 'object', description: 'op:track — {duration?, loop?, iterations?, direction?:"normal"|"alternate", easing?, delay?, anchor?, origin?:"offset"|"first"}.', properties: {} },
        keyframe:     { type: 'object', description: 'op:keyframe — {t:ms, x?, y?, opacity?, scale?, rotation?, blur?, draw?, easing?, hold?}.', properties: {} },
        stagger_ms:   { type: 'number', description: 'op:motion/track — delay between consecutive layers, ms. 60–120 reads well for a list. op:link — extra lag per follower, so a row trails like a whip.' },
        order:        { type: 'string', enum: ['forward', 'reverse', 'center', 'edges', 'random', 'left_to_right', 'right_to_left', 'top_to_bottom', 'bottom_to_top'], description: 'op:motion/track (and each op:sequence step) — which layer the stagger starts from. forward = the order listed; center opens from the middle with mirrored pairs together; edges closes in; random is seeded by the ids (same every call); the *_to_* orders follow where layers sit, so split_text letters sweep by position.' },
        by:           { type: 'string', enum: ['char', 'word', 'line'], description: 'op:text — the unit to animate. char (default) and word are placed by the font\'s measured advances; line follows the wrap the renderer draws, so a paragraph animates line by line.' },
        mask:         { type: 'boolean', description: 'op:text — put each unit behind its own fixed clip, so it rises or slides in from under an edge (a track matte per unit).' },
        keep_source:  { type: 'boolean', description: 'op:text — keep the original text layer, hidden, instead of replacing it with the units.' },
        remeasure:    { type: 'boolean', description: 'op:text — re-place pieces split EARLIER (<layer>_w1…/_c1…) with today\'s font widths, keeping their motion and masks; layer_id names one split, without it every split in the design (page_id narrows). Needed for text split before 2026-09-15, when exports drew variable fonts at their default weight and the pieces were measured narrow.' },
        amplitude:    { type: 'object', properties: { x: { type: 'number' }, y: { type: 'number' }, rotation: { type: 'number' }, scale: { type: 'number' } }, description: 'op:wiggle — how far each channel may stray: px for x/y, degrees for rotation, a ratio for scale (0.04 = ±4%). At least one.' },
        frequency:    { type: 'number', description: 'op:wiggle — wiggles per second (default 2).' },
        seed:         { type: 'string', description: 'op:wiggle — re-roll the noise. Without it a layer wiggles the same way on every call and export.' },
        shots:        { type: 'array', items: { type: 'object', properties: {} }, description: 'op:storyboard — [{id?, at, states:{<layer id>: {x?, y?, dx?, dy?, scale?, rotation?, opacity?, enter?, exit?, loop?, loop_ms?, hidden?, duration?, delay?, easing?} | "hidden" | "show" | "still" | "<preset>"}, duration?, easing?, stagger_ms?, order?, hold?}] in time order; at is ms or a name ("hook+4000"). op:camera — [{t:ms|name, target:"all"|"world"|id|[ids]|{x,y,width,height}, padding?:px, easing?, hold?, rotation?:deg}]. Each camera shot frames its target to fill the canvas; the camera eases between shots. `rotation` turns the world about its centre and the framing follows, so a shot can arrive tilted (it carries to later shots until one changes it) — a dive that spirals, not just pushes. e.g. [{t:0,target:"all"},{t:1200,target:"stat",padding:80},{t:3000,target:"all"}].' },
        markers:      { type: 'object', properties: {}, description: 'op:markers — name → time to set, e.g. {hook:0, problem:4000, cta:"problem+6000"}; null removes one. Names: letters, digits, _ and -.' },
        at:           { type: 'string', description: 'op:retime — where to open or close time: ms ("31300") or a name ("result+3000"). Put it in a rest.' },
        shift_ms:     { type: 'number', description: 'op:retime — ms to open at `at` (positive: everything after it moves later) or to close after it (negative).' },
        in:           { type: 'string', description: 'op:span — the in point: ms ("4000") or a name ("problem", "title.out+200"). The layer does not exist before it.' },
        out:          { type: 'string', description: 'op:span — the out point: ms or a name. The layer is gone from here on.' },
        start:        { type: 'string', description: 'op:precomp — when the precomp\'s local 0 falls on the scene clock: ms or a name.' },
        speed:        { type: 'number', description: 'op:precomp — local ms per scene ms: 2 plays the sub-sequence twice as fast (default 1).' },
        loop_ms:      { type: 'number', description: 'op:precomp — repeat the sub-sequence every this many LOCAL ms (0 stops the loop).' },
        duplicate:    { type: 'object', properties: { id: { type: 'string' }, start: { type: 'string' }, dx: { type: 'number' }, dy: { type: 'number' } }, description: 'op:precomp — place a second instance of the precomp: {id, start?, dx?, dy?}. Child ids get the new id as a suffix.' },
        channels:     { type: 'array', items: { type: 'string', enum: ['x', 'y', 'rotation', 'scale', 'scale_x', 'scale_y', 'skew_x', 'skew_y', 'opacity', 'blur'] }, description: 'op:link — which of the target\'s channels to follow (default x, y, rotation, scale).' },
        lag:          { type: 'number', description: 'op:link — ms behind the target (default 100). 60–150 reads as follow-through.' },
        factor:       { type: 'number', description: 'op:link — how far the follower travels, as a fraction of the target\'s travel (default 1; 0.5 = half, a trailing drag; negative mirrors).' },
        world:        { type: 'object', properties: { x: { type: 'number' }, y: { type: 'number' }, width: { type: 'number' }, height: { type: 'number' } }, description: 'op:camera — the layout area the camera travels over, larger than the canvas: {x, y, width, height} in canvas px, "auto" (the content\'s bounds) or "none". Stored on the page; the off-canvas rescue leaves content inside it alone.' },
        exclude:      { type: 'array', items: { type: 'string' }, description: 'op:camera — layers that stay still while the camera moves. The full-canvas page ground is always kept out.' },
        padding:      { type: 'number', description: 'op:camera — default space kept around each shot\'s target, px.' },
        to:           { type: 'string', description: 'op:morph — the outline to become, as an SVG `d` string (no elliptical arcs). op:link — the id of the layer to follow.' },
        to_layer:     { type: 'string', description: 'op:morph — or: the id of a path layer whose outline to become. It is hidden, so only the changing shape shows.' },
        keep_target:  { type: 'boolean', description: 'op:morph — leave the to_layer visible.' },
        delay:        { type: 'number', description: 'op:morph — when the shape starts to change, ms from the start of the SCENE (the clock op:sequence `at` uses). It must not overlap motion the layer already has; the reply gives from_ms/to_ms. op:motion_path — ms before the layer sets off along the path (inside a precomp, on its clock).' },
        easing:       { type: 'string', description: 'op:motion — curve name (see the vocabulary above) or cubic-bezier(...). Per-preset default if omitted.' },
        distance:     { type: 'number', description: 'op:motion — travel distance in px for travelling presets. Per-preset default if omitted.' },
        duration:     { type: 'number', description: 'op:motion — run length ms. op:export — total clip length ms (default: the scene length; raster formats max 60000). op:audio — how long the sound plays, ms (default: the rest of the file; a loop runs to the end of the piece).' },
        t:            { type: 'number', description: 'op:frame — time to render, ms from scene start (default 0).' },
        frames:       { type: 'number', description: 'op:preview — how many poses to sample across the scene (2-24, default 6).' },
        cell:         { type: 'number', description: 'op:preview — longest edge of each filmstrip cell in px (80-480, default 260).' },
        strip_only:   { type: 'boolean', description: 'op:preview — return only the inline filmstrip, skipping the .preview.gif file.' },
        scale:        { type: 'number', description: 'op:frame — raster scale 0.25–2 (default 1). op:export gif/mp4/webm — output size as a fraction of the canvas, 0.1–1 (default 1): 0.5 renders a 1920×1080 piece at 960×540, a quarter of the pixels to render and to download. A scaled export, or one at a non-default fps, is written to its own file (…-960x540-20fps.gif).' },
        type:         { type: 'string', enum: ['svg', 'html', 'gif', 'mp4', 'webm'], description: 'op:export — output format. svg = self-contained animated SVG. html = the same in a shareable page honoring prefers-reduced-motion. gif = raster flipbook, streamed in-process. mp4 (H.264) / webm (VP9) = the same frames piped into ffmpeg.' },
        all_pages:    { type: 'boolean', description: 'op:export — one animated file per carousel page (`<name>-p1.gif`, …).' },
        output_path:  { type: 'string', description: 'op:export/frame — output file path (auto if omitted; frame returns inline when omitted).' },
        fps:          { type: 'number', description: 'op:export — frames per second (gif: default 12, max 50 · mp4/webm: default 30, max 60). 12 looks stepped on fast motion: 20–25 plays smoothly in a GIF, 24–30 in a video. Frames cost render time and bytes, so lower the scale before the fps.' },
        scenes:       { type: 'boolean', description: 'op:export/frame/timeline — treat every page, in order, as one multi-scene piece.' },
        hold_ms:      { type: 'number', description: 'op:export/frame/timeline with scenes — rest after each scene\'s motion, ms (default 1500; a page\'s length_ms wins). op:storyboard — rest after the last move lands (default 2500).' },
        background:   { type: 'boolean', description: 'op:export (gif/mp4/webm) — true renders as a background job and replies at once with a job_id; false waits for the file. Default: a job when the clip is over 150 frames.' },
        job_id:       { type: 'string', description: 'op:export_status — the job_id a background export replied with.' },
        transition:   { type: 'object', description: 'op:scene — how the page ENTERS: {type, duration?: ms (default 400, max 3000), easing?}. type "none" = a cut.', properties: { type: { type: 'string', enum: ['none', 'fade', 'slide-left', 'slide-right', 'slide-up', 'slide-down', 'zoom-in', 'zoom-out', 'flip-h', 'flip-v', 'cube-left', 'cube-right', 'reveal', 'wipe-left', 'wipe-right', 'dissolve', 'morph'] }, duration: { type: 'number' }, easing: { type: 'string' } } },
        length_ms:    { type: 'number', description: 'op:scene — exact time the page is on screen, ms. 0 clears it (motion + hold). op:storyboard — the scene\'s total length, ms or a name ("cta+3000"); default: the last move + hold_ms.' },
        src:          { type: 'string', description: 'op:audio — the sound file, as the assets/audio/… (or lib/…) path manage_design(op:asset_add) returned: mp3, wav, m4a, aac, ogg, opus, flac.' },
        audio_id:     { type: 'string', description: 'op:audio — which sound to change or remove (default for a new one: its file name). op:beats — which sound to measure (default: the first track).' },
        remove:       { type: 'boolean', description: 'op:audio — take the sound named by audio_id out (without audio_id: every sound in scope).' },
        start_ms:     { type: 'number', description: 'op:audio — when it starts: ms into the piece, or with page_id ms after that scene\'s first frame (default 0).' },
        offset_ms:    { type: 'number', description: 'op:audio — where in the FILE playback begins, ms (skip an intro).' },
        volume:       { type: 'number', description: 'op:audio — 0 silent … 1 as recorded (default 1). Sounds are summed, not averaged: leave headroom for cues over music.' },
        fade_in:      { type: 'number', description: 'op:audio — fade in over this many ms (linear).' },
        fade_out:     { type: 'number', description: 'op:audio — fade out over this many ms before the sound ends, or before the piece cuts it off.' },
        loop:         { type: 'boolean', description: 'op:audio — repeat the file until duration, or to the end of the piece.' },
      },
      required: ['op'],
    },
  },
];
