import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { batchCreate } from './engine-export-tools';
import { resolveBuiltinTemplate } from './engine/builtin-templates';
import { readYAML } from './engine/utils';
import type { DesignSpec } from '../schema/types';
import type { TemplateSpec } from '../schema/template';

// batch_create historically resolved template_id ONLY as a project .template.yaml
// or a project design to clone — so a built-in CATALOG id (the kind templates
// {op:inject}/{op:slots} happily accept) returned "Template not found". This
// asserts the consistency fix: a catalog id usable for inject also works for batch.

const PUBLIC_BUILTIN = path.resolve('public/templates/builtin');
const INDEX = path.resolve('src/templates/catalog-index.json');
const CATALOG_ID = 'tmpl-1099-form'; // 297-1099-form.template.yaml, generated by `npm run gen`

let projectsDir: string;
const prevDir = process.env['FOLIO_BUILTIN_TEMPLATES_DIR'];
const prevIdx = process.env['FOLIO_BUILTIN_INDEX'];

beforeAll(() => {
  process.env['FOLIO_BUILTIN_TEMPLATES_DIR'] = PUBLIC_BUILTIN;
  process.env['FOLIO_BUILTIN_INDEX'] = INDEX;
  projectsDir = fs.mkdtempSync(path.join(os.tmpdir(), 'batch-builtin-'));
  fs.mkdirSync(path.join(projectsDir, 'designs'), { recursive: true });
});

afterAll(() => {
  if (prevDir === undefined) delete process.env['FOLIO_BUILTIN_TEMPLATES_DIR']; else process.env['FOLIO_BUILTIN_TEMPLATES_DIR'] = prevDir;
  if (prevIdx === undefined) delete process.env['FOLIO_BUILTIN_INDEX']; else process.env['FOLIO_BUILTIN_INDEX'] = prevIdx;
  fs.rmSync(projectsDir, { recursive: true, force: true });
});

describe('batch_create accepts a built-in catalog id (parity with inject/slots)', () => {
  it('clones a catalog template into N variants, inheriting its dimensions', () => {
    const tplPath = resolveBuiltinTemplate(CATALOG_ID);
    expect(tplPath, 'precondition: catalog asset present (run `npm run gen`)').toBeTruthy();
    const tpl = readYAML<TemplateSpec>(tplPath!);

    const res = batchCreate({
      project_path: projectsDir, template_id: CATALOG_ID,
      slots_array: [{ name: 'variant-a' }, { name: 'variant-b' }],
    });

    expect((res as { success?: boolean }).success).not.toBe(false);
    const created = (res as unknown as { created: { path: string }[] }).created;
    expect(created).toHaveLength(2);
    for (const c of created) {
      const spec = readYAML<DesignSpec>(c.path);
      expect([spec.document.width, spec.document.height])
        .toEqual([tpl.document.width, tpl.document.height]);
    }
  });
});
