import { describe, it, expect } from 'vitest';
import { footerHref, normalizeUrl } from './shorthand-helpers';
import { expandShorthand } from './shorthand-expand';
import type { ShorthandLayer } from './shorthand-parser';

describe('normalizeUrl', () => {
  it('adds https:// when missing, keeps an existing scheme', () => {
    expect(normalizeUrl('github.com/x')).toBe('https://github.com/x');
    expect(normalizeUrl('https://a.com')).toBe('https://a.com');
    expect(normalizeUrl('http://a.com')).toBe('http://a.com');
  });
});

describe('footerHref — auto-detect a URL in footer text', () => {
  it('links a bare domain+path (the "repo hyperlink as footer" case)', () => {
    expect(footerHref('github.com/azzindani/Folio', {})).toBe('https://github.com/azzindani/Folio');
  });
  it('links a full http(s) URL and a www host', () => {
    expect(footerHref('Visit https://folio.dev/docs today', {})).toBe('https://folio.dev/docs');
    expect(footerHref('www.example.com/page', {})).toBe('https://www.example.com/page');
  });
  it('honors an explicit footer_link / link field over the text', () => {
    expect(footerHref('My Site', { footer_link: 'example.com/a' })).toBe('https://example.com/a');
    expect(footerHref('My Site', { link: 'https://x.io' })).toBe('https://x.io');
  });
  it('does NOT false-match version strings, filenames or dotted prose', () => {
    expect(footerHref('Folio v2.5.0 · 2026', {})).toBeUndefined();
    expect(footerHref('see design.yaml', {})).toBeUndefined();
    expect(footerHref('made with care, e.g. fast', {})).toBeUndefined();
    expect(footerHref('Generated by Claude Code', {})).toBeUndefined();
  });
});

describe('sections preset — footer becomes a clickable hyperlink', () => {
  function footerLayer(sh: ShorthandLayer): Record<string, unknown> | undefined {
    const grp = expandShorthand(sh) as unknown as { layers?: Record<string, unknown>[] };
    const find = (ls: Record<string, unknown>[]): Record<string, unknown> | undefined => {
      for (const l of ls) {
        if (String(l['id']).endsWith('_footer')) return l;
        if (Array.isArray(l['layers'])) { const f = find(l['layers'] as Record<string, unknown>[]); if (f) return f; }
      }
      return undefined;
    };
    return find(grp.layers ?? []);
  }

  it('sets href on the footer when the footer text is a URL', () => {
    const f = footerLayer({ id: 's', type: 'sections', title: 'T', subtitle: 'x',
      footer: 'github.com/azzindani/Folio', blocks: [{ kind: 'text', text: 'hi' }] } as unknown as ShorthandLayer);
    expect(f?.['href']).toBe('https://github.com/azzindani/Folio');
  });

  it('leaves a plain-text footer un-linked', () => {
    const f = footerLayer({ id: 's', type: 'sections', title: 'T', subtitle: 'x',
      footer: 'Made with Folio', blocks: [{ kind: 'text', text: 'hi' }] } as unknown as ShorthandLayer);
    expect(f?.['href']).toBeUndefined();
  });
});
