// AI-slop lint — catches the "looks generated by default" tells in a Folio spec,
// the post-design counterpart to the craft/anti_slop rulebook the model reads up
// front (see ./craft). Translated from Open Design's lint-artifact cardinal sins
// (nexu-io, Apache-2.0; rules from MIT refero_skill) onto Folio's layer/fill model
// — HTML-DOM-only checks (section anchors, scroll-into-view) are dropped.
//
// Pure — no I/O. Reuses the color math from ./reference. Returns advisory notes;
// surfaced as diagnose_design findings + add_layers review notes so the model
// self-corrects. Conservative on purpose (clear tells only), so it guides without
// nagging a legitimately bold design (CLAUDE.md §0.4 — the look is the model's).

import type { Layer } from '../../schema/types';
import { hexToRgb, hue, saturation, type RGB } from './reference';

// The Tailwind indigo/violet family — the single most common AI accent tell.
const AI_INDIGO = ['#6366f1', '#4f46e5', '#4338ca', '#3730a3', '#8b5cf6', '#7c3aed', '#a855f7'];
const AI_INDIGO_RGB = AI_INDIGO.map(hexToRgb).filter((r): r is RGB => r !== null);

const EMOJI = /[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{2B00}-\u{2BFF}\u{FE0F}\u{200D}\u{2190}-\u{21FF}\u{2300}-\u{23FF}]/u;
const EMOJI_G = new RegExp(EMOJI, 'gu');

const INVENTED_METRIC = [
  /\b\d+(\.\d+)?\s?[×x]\b/i,                          // 10×, 3x
  /\b\d{2,3}(\.\d+)?\s?%\s*(uptime|faster|slower|more|less|growth|accuracy|roi)/i,
  /\b99\.9+\s?%/,                                      // 99.9% …
  /\b\d+(\.\d+)?[×x]\s+(faster|more|better|productive|cheaper)/i,
];
const FILLER_COPY = /lorem ipsum|feature (one|two|three|1|2|3)\b|placeholder text|sample content|your (text|title|headline) here|tagline goes here|body copy here/i;

function rgbDist(a: RGB, b: RGB): number {
  return Math.sqrt((a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2 + (a[2] - b[2]) ** 2);
}
function nearIndigo(rgb: RGB): boolean {
  return AI_INDIGO_RGB.some(i => rgbDist(rgb, i) < 26);
}

/** Flatten the layer tree (presets/groups nest the real content). */
function flatten(layers: Layer[], out: Layer[] = []): Layer[] {
  for (const l of layers) {
    out.push(l);
    const kids = (l as { layers?: Layer[] }).layers;
    if (Array.isArray(kids)) flatten(kids, out);
  }
  return out;
}

/** First hex of a solid/pattern/first-stop fill, or a top-level shape `color`. */
function solidHex(l: Layer): string | null {
  const f = (l as { fill?: unknown }).fill;
  if (typeof f === 'string') return f.startsWith('#') ? f : null;
  if (f && typeof f === 'object') {
    const o = f as { type?: string; color?: string; bg?: string; fg?: string; stops?: { color?: string }[] };
    if (typeof o.color === 'string' && o.color.startsWith('#')) return o.color;
    if (o.type === 'pattern' && typeof (o.fg ?? o.bg) === 'string' && (o.fg ?? o.bg)!.startsWith('#')) return o.fg ?? o.bg!;
    const s = o.stops?.[0]?.color;
    if (typeof s === 'string' && s.startsWith('#')) return s;
  }
  if (f === undefined) {
    const c = (l as { color?: unknown }).color;
    if (typeof c === 'string' && c.startsWith('#')) return c;
  }
  return null;
}

function gradientStops(l: Layer): string[] {
  const f = (l as { fill?: unknown }).fill;
  if (f && typeof f === 'object') {
    const o = f as { type?: string; stops?: { color?: string }[] };
    if ((o.type === 'linear' || o.type === 'radial' || o.type === 'conic') && Array.isArray(o.stops)) {
      return o.stops.map(s => s.color).filter((c): c is string => typeof c === 'string' && c.startsWith('#'));
    }
  }
  return [];
}

function textColor(l: Layer): string | null {
  const c = (l as { style?: { color?: unknown } }).style?.color;
  return typeof c === 'string' && c.startsWith('#') ? c : null;
}
function textValue(l: Layer): string {
  const v = (l as { content?: { value?: unknown } }).content?.value;
  return typeof v === 'string' ? v : '';
}
function isUpper(l: Layer, v: string): boolean {
  if ((l as { style?: { text_transform?: string } }).style?.text_transform === 'uppercase') return true;
  const letters = v.replace(/[^A-Za-z]/g, '');
  return letters.length >= 4 && letters === letters.toUpperCase() && /[A-Z]/.test(letters);
}

/** A single saturated-hue "bucket" (30° wide) for accent-overuse counting. */
function vividBucket(hex: string): number | null {
  const rgb = hexToRgb(hex);
  if (!rgb || saturation(rgb) < 0.45) return null;
  return Math.round(hue(rgb) / 30);
}

/** Returns AI-slop notes (empty = clean). Capped so it guides, not nags. */
export function lintAiSlop(layers: Layer[]): string[] {
  const notes: string[] = [];
  const all = flatten(layers);

  // 1. Default-indigo accent — the textbook tell.
  const indigoHit = all.map(l => solidHex(l) ?? textColor(l)).find(h => {
    const rgb = h ? hexToRgb(h) : null;
    return rgb ? nearIndigo(rgb) : false;
  });
  if (indigoHit) {
    notes.push(`accent ${indigoHit} is default Tailwind indigo/violet — THE textbook AI tell. Swap it for the theme's accent or a real brand hue (anti_slop rule 1).`);
  }

  // 2. Two-stop "trust" gradient (purple→blue / blue→cyan / indigo→pink).
  for (const l of all) {
    const stops = gradientStops(l);
    if (stops.length < 2) continue;
    const hs = stops.map(hexToRgb).filter((r): r is RGB => !!r)
      .filter(r => saturation(r) > 0.3).map(hue);
    const violet = hs.some(h => h >= 248 && h <= 302);
    const cyanBlue = hs.some(h => h >= 185 && h <= 205) && hs.some(h => h >= 205 && h <= 238);
    if ((violet && hs.length >= 2) || cyanBlue) {
      notes.push(`layer "${l.id}" is a two-stop purple/blue "trust" gradient — the AI gradient cliché. Use a flat surface + a pattern/texture fill, or a tonal one-hue gradient off the text (anti_slop rule 2).`);
      break;
    }
  }

  // 3. Emoji used as an icon (a text layer that is PURE emoji).
  const emojiIcon = all.find(l => {
    if (l.type !== 'text') return false;
    const v = textValue(l).trim();
    return EMOJI.test(v) && v.replace(EMOJI_G, '').trim() === '';
  });
  if (emojiIcon) {
    notes.push(`text "${emojiIcon.id}" is an emoji used as an icon — use the \`icon\` layer type (monoline, currentColor) instead of an emoji glyph (anti_slop rule 3).`);
  }

  // 3b. The "image"/"photo" glyph used as a decorative bullet — it renders as
  // a framed mountain+sun that readers parse as a BROKEN THUMBNAIL, not an
  // icon (observed: a blind model marked every feature row with it).
  const brokenLook = all.filter(l => {
    if (l.type !== 'icon') return false;
    const n = String((l as { name?: unknown }).name ?? '').toLowerCase();
    return n === 'image' || n === 'img' || n === 'photo' || n === 'picture' || n === 'pic' || n === 'gallery';
  });
  if (brokenLook.length > 0) {
    notes.push(`icon "${brokenLook[0].id}" uses name:"image" — that glyph reads as a BROKEN image placeholder, not decoration. Pick a semantic icon per item (coffee, package, truck, star, check, zap, …)${brokenLook.length > 1 ? ` — ${brokenLook.length} layers affected` : ''}.`);
  }

  // 4. Invented metrics + 5. Filler copy.
  for (const l of all) {
    if (l.type !== 'text') continue;
    const v = textValue(l).trim();
    if (!v) continue;
    if (FILLER_COPY.test(v)) {
      notes.push(`text "${l.id}" is filler copy ("${v.slice(0, 32)}…") — write real content from the brief; an empty slot is a composition problem, not a place for lorem (anti_slop rule 7).`);
    } else if (INVENTED_METRIC.some(re => re.test(v))) {
      notes.push(`text "${l.id}" looks like an invented metric ("${v.slice(0, 32)}") — use a real figure from the brief/research or a labelled placeholder (anti_slop rule 6).`);
    }
    if (notes.length >= 6) break;
  }

  // 6. ALL-CAPS without tracking — a tell, and it reads cramped.
  const capsNoTrack = all.find(l => {
    if (l.type !== 'text') return false;
    const v = textValue(l).trim();
    if (!v || !isUpper(l, v)) return false;
    const ls = (l as { style?: { letter_spacing?: number; font_size?: number } }).style;
    const size = typeof ls?.font_size === 'number' ? ls.font_size : 16;
    const track = typeof ls?.letter_spacing === 'number' ? ls.letter_spacing : 0;
    return track < Math.max(1, size * 0.04);   // ~0.06em floor, conservative
  });
  if (capsNoTrack && notes.length < 7) {
    notes.push(`text "${capsNoTrack.id}" is ALL-CAPS with little/no letter_spacing — caps always needs ≥0.06em tracking (set letter_spacing) or it reads cramped + generic (type rule).`);
  }

  // 7. Accent overuse — one vivid hue spread across many layers.
  const counts = new Map<number, number>();
  for (const l of all) {
    for (const hex of [solidHex(l), textColor(l)]) {
      const b = hex ? vividBucket(hex) : null;
      if (b !== null) counts.set(b, (counts.get(b) ?? 0) + 1);
    }
  }
  const worst = [...counts.values()].sort((a, b) => b - a)[0] ?? 0;
  if (worst > 5 && notes.length < 8) {
    notes.push(`one accent hue appears on ${worst} layers — cap visible accent uses at ~2 per surface (one eyebrow/chip + one CTA); let neutrals carry 70–90% (color rule).`);
  }

  return notes.slice(0, 6);
}
