// AI-slop lint — catches the "looks generated by default" tells in a Folio spec,
// the post-design counterpart to the craft/anti_slop rulebook the model reads up
// front (see ./craft). Translated from Open Design's lint-artifact cardinal sins
// (nexu-io, Apache-2.0; rules from MIT refero_skill) onto Folio's layer/fill model
// — HTML-DOM-only checks (section anchors, scroll-into-view) are dropped.
//
// Pure — no I/O. Reuses the color math from ./reference. Returns advisory notes;
// surfaced as diagnose_design findings + add_layers review notes so the model
// self-corrects. Conservative on purpose (clear tells only), so it guides without
// nagging a legitimately bold design (CLAUDE.md §0.4 — the look is the model's).

import type { Layer } from '../../schema/types';
import { layerText } from '../../schema/layer-text';
import { hexToRgb, hue, saturation, type RGB } from './reference';
import { isDisplaySize } from './caps-tracking';

// The Tailwind indigo/violet family — the single most common AI accent tell.
const AI_INDIGO = ['#6366f1', '#4f46e5', '#4338ca', '#3730a3', '#8b5cf6', '#7c3aed', '#a855f7'];
const AI_INDIGO_RGB = AI_INDIGO.map(hexToRgb).filter((r): r is RGB => r !== null);

const EMOJI = /[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{2B00}-\u{2BFF}\u{FE0F}\u{200D}\u{2190}-\u{21FF}\u{2300}-\u{23FF}]/u;
const EMOJI_G = new RegExp(EMOJI, 'gu');
/** Arrows and technical signs with no emoji selector are type ("→", "⌘"), not emoji (Opus 5.5 promo: a receipt's → was flagged). */
const TYPOGRAPHIC = /^[\u{2190}-\u{21FF}\u{2300}-\u{23FF}\s]+$/u;

const INVENTED_METRIC = [
  /\b\d+(\.\d+)?\s?[×x]\b/i,                          // 10×, 3x
  /\b\d{2,3}(\.\d+)?\s?%\s*(uptime|faster|slower|more|less|growth|accuracy|roi)/i,
  /\b99\.9+\s?%/,                                      // 99.9% …
  /\b\d+(\.\d+)?[×x]\s+(faster|more|better|productive|cheaper)/i,
];
const FILLER_COPY = /lorem ipsum|feature (one|two|three|1|2|3)\b|placeholder text|sample content|your (text|title|headline) here|tagline goes here|body copy here/i;

function rgbDist(a: RGB, b: RGB): number {
  return Math.sqrt((a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2 + (a[2] - b[2]) ** 2);
}
function nearIndigo(rgb: RGB): boolean {
  return AI_INDIGO_RGB.some(i => rgbDist(rgb, i) < 26);
}

/** Flatten the layer tree (presets/groups nest the real content). */
function flatten(layers: Layer[], out: Layer[] = []): Layer[] {
  for (const l of layers) {
    out.push(l);
    const kids = (l as { layers?: Layer[] }).layers;
    if (Array.isArray(kids)) flatten(kids, out);
  }
  return out;
}

/** Is this design citing a dataset? A figure on a sourced page is evidence, not
 *  invention — the rule must not call a real number made up because it looks
 *  round. (Review: "invented metric" fired on data-backed board-deck figures.) */
function isSourced(all: Layer[]): boolean {
  return all.some(l => l.type === 'text' && /\b(source|sources|data|dataset|per|according to|n\s*=)\s*[:=]/i.test(textValue(l)));
}

/** First hex of a solid/pattern/first-stop fill, or a top-level shape `color`. */
function solidHex(l: Layer): string | null {
  const f = (l as { fill?: unknown }).fill;
  if (typeof f === 'string') return f.startsWith('#') ? f : null;
  if (f && typeof f === 'object') {
    const o = f as { type?: string; color?: string; bg?: string; fg?: string; stops?: { color?: string }[] };
    if (typeof o.color === 'string' && o.color.startsWith('#')) return o.color;
    if (o.type === 'pattern' && typeof (o.fg ?? o.bg) === 'string' && (o.fg ?? o.bg)!.startsWith('#')) return o.fg ?? o.bg!;
    const s = o.stops?.[0]?.color;
    if (typeof s === 'string' && s.startsWith('#')) return s;
  }
  if (f === undefined) {
    const c = (l as { color?: unknown }).color;
    if (typeof c === 'string' && c.startsWith('#')) return c;
  }
  return null;
}

function gradientStops(l: Layer): string[] {
  const f = (l as { fill?: unknown }).fill;
  if (f && typeof f === 'object') {
    const o = f as { type?: string; stops?: { color?: string }[] };
    if ((o.type === 'linear' || o.type === 'radial' || o.type === 'conic') && Array.isArray(o.stops)) {
      return o.stops.map(s => s.color).filter((c): c is string => typeof c === 'string' && c.startsWith('#'));
    }
  }
  return [];
}

function textColor(l: Layer): string | null {
  const c = (l as { style?: { color?: unknown } }).style?.color;
  return typeof c === 'string' && c.startsWith('#') ? c : null;
}
/** Every content shape — a scalar or rich-text layer is still copy, and the
 *  slop checks below (uppercase shouting, em-dash tells) must see it. */
const textValue = (l: Layer): string => layerText(l);
function isUpper(l: Layer, v: string): boolean {
  if ((l as { style?: { text_transform?: string } }).style?.text_transform === 'uppercase') return true;
  const letters = v.replace(/[^A-Za-z]/g, '');
  return letters.length >= 4 && letters === letters.toUpperCase() && /[A-Z]/.test(letters);
}

/** A single saturated-hue "bucket" (30° wide) for accent-overuse counting. */
function vividBucket(hex: string): number | null {
  const rgb = hexToRgb(hex);
  // HSL saturation runs high for near-white tints: #E6F0FA scores 0.66, and a
  // how-to's pale icon discs and idle progress bars counted as brand-blue accents
  // (benchmark r6, b23). Chroma — how far from grey — is what the eye reads as colour.
  const chroma = rgb ? (Math.max(...rgb) - Math.min(...rgb)) / 255 : 0;
  if (!rgb || saturation(rgb) < 0.45 || chroma < 0.25) return null;
  return Math.round(hue(rgb) / 30);
}

/** Returns AI-slop notes (empty = clean). Capped so it guides, not nags.
 *  `canvasShort` (the canvas's short side) tells display caps from text caps. */
export function lintAiSlop(layers: Layer[], canvasShort?: number): string[] {
  const notes: string[] = [];
  const all = flatten(layers);

  // 1. Default-indigo accent — the textbook tell.
  const indigoHit = all.map(l => solidHex(l) ?? textColor(l)).find(h => {
    const rgb = h ? hexToRgb(h) : null;
    return rgb ? nearIndigo(rgb) : false;
  });
  if (indigoHit) {
    notes.push(`accent ${indigoHit} is default Tailwind indigo/violet — THE textbook AI tell. Swap it for the theme's accent or a real brand hue (anti_slop rule 1).`);
  }

  // 2. Two-stop "trust" gradient (purple→blue / blue→cyan / indigo→pink).
  for (const l of all) {
    const stops = gradientStops(l);
    if (stops.length < 2) continue;
    const hs = stops.map(hexToRgb).filter((r): r is RGB => !!r)
      .filter(r => saturation(r) > 0.3).map(hue);
    const violet = hs.some(h => h >= 248 && h <= 302);
    const cyanBlue = hs.some(h => h >= 185 && h <= 205) && hs.some(h => h >= 205 && h <= 238);
    if ((violet && hs.length >= 2) || cyanBlue) {
      notes.push(`layer "${l.id}" is a two-stop purple/blue "trust" gradient — the AI gradient cliché. Use a flat surface + a pattern/texture fill, or a tonal one-hue gradient off the text (anti_slop rule 2).`);
      break;
    }
  }

  // 3. Emoji used as an icon (a text layer that is PURE emoji).
  const emojiIcon = all.find(l => {
    if (l.type !== 'text') return false;
    const v = textValue(l).trim();
    return EMOJI.test(v) && v.replace(EMOJI_G, '').trim() === '' && !TYPOGRAPHIC.test(v);
  });
  if (emojiIcon) {
    notes.push(`text "${emojiIcon.id}" is an emoji used as an icon — use the \`icon\` layer type (monoline, currentColor) instead of an emoji glyph (anti_slop rule 3).`);
  }

  // 3b. The "image"/"photo" glyph used as a decorative bullet — it renders as
  // a framed mountain+sun that readers parse as a BROKEN THUMBNAIL, not an
  // icon (observed: a blind model marked every feature row with it).
  const brokenLook = all.filter(l => {
    if (l.type !== 'icon') return false;
    const n = String((l as { name?: unknown }).name ?? '').toLowerCase();
    return n === 'image' || n === 'img' || n === 'photo' || n === 'picture' || n === 'pic' || n === 'gallery';
  });
  if (brokenLook.length > 0) {
    notes.push(`icon "${brokenLook[0].id}" uses name:"image" — that glyph reads as a BROKEN image placeholder, not decoration. Pick a semantic icon per item (coffee, package, truck, star, check, zap, …)${brokenLook.length > 1 ? ` — ${brokenLook.length} layers affected` : ''}.`);
  }

  // 4. Unlabelled metrics + 5. Filler copy.
  const sourced = isSourced(all);
  for (const l of all) {
    if (l.type !== 'text') continue;
    const v = textValue(l).trim();
    if (!v) continue;
    if (FILLER_COPY.test(v)) {
      notes.push(`text "${l.id}" is filler copy ("${v.slice(0, 32)}…") — write real content from the brief; an empty slot is a composition problem, not a place for lorem (anti_slop rule 7).`);
    } else if (!sourced && INVENTED_METRIC.some(re => re.test(v))) {
      notes.push(`text "${l.id}" is an UNLABELLED metric ("${v.slice(0, 32)}") — nothing on the page says where it came from. Cite it (a "Source: …" line, or the dataset name) or drop it (anti_slop rule 6).`);
    }
    if (notes.length >= 6) break;
  }

  // 6. ALL-CAPS at text sizes without tracking — a tell, and it reads cramped.
  // Display caps are left alone: tight tracking on a big headline is a choice.
  const capsNoTrack = all.find(l => {
    if (l.type !== 'text') return false;
    const v = textValue(l).trim();
    if (!v || !isUpper(l, v)) return false;
    const ls = (l as { style?: { letter_spacing?: number; font_size?: number } }).style;
    const size = typeof ls?.font_size === 'number' ? ls.font_size : 16;
    if (isDisplaySize(size, canvasShort)) return false;
    const track = typeof ls?.letter_spacing === 'number' ? ls.letter_spacing : 0;
    return track < Math.max(1, size * 0.04);   // ~0.06em floor, conservative
  });
  if (capsNoTrack && notes.length < 7) {
    notes.push(`text "${capsNoTrack.id}" is ALL-CAPS at text size with little/no letter_spacing — caps this small wants ≥0.06em tracking (set letter_spacing) or it reads cramped + generic (type rule).`);
  }

  // 7. Accent overuse — one vivid hue spread across many surfaces (accentNote).
  const accent = accentNote(layers);
  if (accent && notes.length < 8) notes.push(accent);

  return notes.slice(0, 6);
}

/** Top-level shapes drawn over one another are one object — a cookie and the marks on it (r2, b07) — keyed by
 *  the object; a ground spanning the whole piece joins nothing. Layers with no box are left out. */
function objects(ls: Layer[]): Map<Layer, string> {
  type B = { l: Layer; x: number; y: number; w: number; h: number };
  const boxed: B[] = ls.flatMap(l => {
    const o = l as unknown as { x?: number; y?: number; width?: number; height?: number };
    return typeof o.width === 'number' && typeof o.height === 'number' ? [{ l, x: o.x ?? 0, y: o.y ?? 0, w: o.width, h: o.height }] : [];
  });
  if (boxed.length < 2) return new Map();
  const x0 = Math.min(...boxed.map(b => b.x)), y0 = Math.min(...boxed.map(b => b.y));
  const extent = (Math.max(...boxed.map(b => b.x + b.w)) - x0) * (Math.max(...boxed.map(b => b.y + b.h)) - y0);
  const parts = boxed.filter(b => b.w * b.h < 0.9 * extent);
  const root = parts.map((_, i) => i);
  const find = (i: number): number => (root[i] === i ? i : (root[i] = find(root[i] ?? i)));
  parts.forEach((a, i) => parts.forEach((b, j) => {
    if (j > i && Math.min(a.x + a.w, b.x + b.w) > Math.max(a.x, b.x) && Math.min(a.y + a.h, b.y + b.h) > Math.max(a.y, b.y)) root[find(i)] = find(j);
  }));
  const size = new Map<number, number>();
  parts.forEach((_, i) => size.set(find(i), (size.get(find(i)) ?? 0) + 1));
  const out = new Map<Layer, string>();
  parts.forEach((b, i) => { if ((size.get(find(i)) ?? 0) > 1) out.set(b.l, `object:${parts[find(i)]?.l.id ?? b.l.id}`); });
  return out;
}

/** A surface's key for accent counting: its container — or, for a run of ≥3 siblings drawn alike (same
 *  kind, size, colour), the run: five identical timeline dots are one decision, not five (r7, b28). */
function surfaceKeys(layers: Layer[]): Map<Layer, string> {
  const keys = new Map<Layer, string>();
  const sig = (l: Layer): string => {
    const o = l as unknown as { width?: number; height?: number };
    return `${l.type}:${Math.round(o.width ?? 0)}x${Math.round(o.height ?? 0)}:${solidHex(l) ?? textColor(l) ?? ''}`;
  };
  // Containers alike in what they hold (kind, and each child's kind and colour) are one series too, whatever
  // their size: a timetable's cards run as long as their acts, and 15 alike time labels were 15 uses (r8, b31).
  const holds = (l: Layer): string | null => {
    const kids = (l as { layers?: Layer[] }).layers;
    return Array.isArray(kids) ? `${l.type}|${kids.map(k => `${k.type}:${solidHex(k) ?? textColor(k) ?? ''}`).join(',')}` : null;
  };
  const walk = (ls: Layer[], parent: string): void => {
    const count = new Map<string, number>(), alike = new Map<string, number>();
    for (const l of ls) {
      count.set(sig(l), (count.get(sig(l)) ?? 0) + 1);
      const h = holds(l);
      if (h) alike.set(h, (alike.get(h) ?? 0) + 1);
    }
    const object = parent === '' ? objects(ls) : new Map<Layer, string>();
    for (const l of ls) {
      keys.set(l, parent !== '' ? parent : object.get(l) ?? ((count.get(sig(l)) ?? 0) >= 3 ? `series:${sig(l)}` : l.id));
      const kids = (l as { layers?: Layer[] }).layers;
      const h = holds(l);
      // One series wherever the cards sit: a stage's column and the next stage's hold the same cards.
      if (Array.isArray(kids)) walk(kids, h && (alike.get(h) ?? 0) >= 3 ? `series:${h}` : l.id);
    }
  };
  walk(layers, '');
  return keys;
}

/** The most surfaces one vivid hue is on. Counted per container, not per layer: a bar
 *  chart's twelve bars in one accent are a single, correct decision (a series wants one
 *  colour), and counting them as twelve fired this rule on every chart ever drawn. */
function accentSpread(layers: Layer[]): number {
  const surfaces = new Map<number, Set<string>>();
  for (const [l, key] of surfaceKeys(layers)) {
    for (const hex of [solidHex(l), textColor(l)]) {
      const b = hex ? vividBucket(hex) : null;
      if (b === null) continue;
      const seen = surfaces.get(b) ?? new Set<string>();
      seen.add(key);
      surfaces.set(b, seen);
    }
  }
  return [...surfaces.values()].map(s => s.size).sort((a, b) => b - a)[0] ?? 0;
}

/** What a frame shows: hidden layers and faded-out subtrees dropped. */
function seen(layers: Layer[]): Layer[] {
  return layers.flatMap(l => {
    const o = l as unknown as { visible?: boolean; opacity?: number; layers?: Layer[] };
    if (o.visible === false || (typeof o.opacity === 'number' && o.opacity <= 0.05)) return [];
    return Array.isArray(o.layers) ? [{ ...l, layers: seen(o.layers) } as Layer] : [l];
  });
}

/**
 * The accent-overuse note, or null. A moving piece is judged by what is on screen
 * together — the most surfaces at any of `frames` (its shot rests) — not by every
 * layer it ever shows: b27's six mint surfaces were never more than three at once (r7).
 */
export function accentNote(layers: Layer[], frames?: Layer[][]): string | null {
  const worst = frames?.length ? Math.max(...frames.map(f => accentSpread(seen(f)))) : accentSpread(layers);
  return worst > 5
    ? `one accent hue appears on ${worst} layers${frames?.length ? ' at once' : ''} — cap visible accent uses at ~2 per surface (one eyebrow/chip + one CTA); let neutrals carry 70–90% (color rule).`
    : null;
}

