// Craft knowledge — brand-agnostic, universal design rules the model carries
// BEFORE it designs (vs design-lint, which catches violations AFTER). Adapted
// for Folio's spec model: tokens are `$token`, fills/type live in the YAML, the
// look is the MODEL's call — these are the universal rules a competent designer
// applies on top (CLAUDE.md §0.4: model designs, engine assists).
//
// Three axes, mirrored from Open Design (nexu-io, Apache-2.0); craft content
// distilled from the MIT refero_skill (© Refero Design), re-grounded to Folio
// tokens + layer types:
//   preset (SHAPE) × theme (BRAND visual language) × craft (UNIVERSAL rules).
//
// Modules are tiny + opt-in so a caller pays token cost only for what it needs:
// get_engine_guide({section:"craft"}) for the index, or section:"anti_slop" |
// "color" | "type" | "ux_laws" | "a11y" for one rulebook.

const CRAFT: Record<string, string> = {

  craft: `# Craft — the universal rules (read once, apply always)

Three axes shape every Folio design. Keep them straight:
  • PRESET  = SHAPE   — event card · feature_grid · timeline · versus · report …
  • THEME   = BRAND   — palette + type + atmosphere ($tokens, apply_theme)
  • CRAFT   = UNIVERSAL — the rules below, true regardless of preset or theme.
A theme says WHICH colors/fonts. Craft says HOW to use them well — e.g. ALL-CAPS
always needs ≥0.06em tracking, neutrals own 70–90% of the canvas, ONE accent.

## The 80/20 soul rule
Aim for ~80% proven patterns + ~20% one distinctive move. The 20% lives in:
  • ONE bold visual decision — a type choice, a single color, an unexpected proportion.
  • Voice — "Start tracking" beats "Get started"; real nouns beat "Feature one".
  • ONE detail only someone who used the product would add (a status badge phrased
    in the product's own words, a real unit, a specific date).

## The identifiability test
If someone outside the project could screenshot the design and NAME what it's for,
it has soul. If it could be ANY brand's poster, you shipped a template. Folio's whole
reason to exist is to NOT look AI-generated — a generic centered-headline-on-a-gradient
is the failure mode, not the goal.

## The five universal rules (details in the sub-modules)
  1. ONE accent. Neutrals carry 70–90% of pixels. (→ color)
  2. ONE dominant entry point. Hierarchy is CONTRAST between levels, not a list of sizes. (→ type)
  3. No AI tells — no default-indigo accent, no purple→blue "trust" gradient, no emoji
     as icons, no invented "10× faster" metrics, no lorem filler. (→ anti_slop)
  4. Compose to the eye's limits — ≤7±2 choices, group by proximity, anchor the primary
     action where scanning lands. (→ ux_laws)
  5. Interactive output meets a11y gates — contrast, focus, labels. (→ a11y)

Sub-modules: get_engine_guide({section:"anti_slop" | "color" | "type" | "ux_laws" | "a11y"}).`,

  anti_slop: `# Anti-AI-slop — the tells that scream "generated by default"

Concrete, checkable. design-lint + diagnose_design flag several of these; the rest are
judgment. Folio's mission is to NOT look AI-made, so treat these as hard rules.

## The seven cardinal sins (P0 — never ship)
1. DEFAULT-INDIGO ACCENT — the Tailwind indigo family (#6366f1 #4f46e5 #4338ca #3730a3
   #8b5cf6 #7c3aed #a855f7) as the accent. It is THE textbook AI tell. Use the theme's
   accent ($accent / a real brand hue), not stock indigo.
2. TWO-STOP "TRUST" GRADIENT — purple→blue, blue→cyan, indigo→pink on the hero/background.
   A flat surface + intentional type beats it every time. (Folio texture/pattern fills read
   far more designed — see the guide's "Texture & variety" section.)
3. EMOJI AS ICONS — ✨🚀🎯⚡🔥💡 standing in for feature/section icons. Use the \`icon\` layer
   type (monoline, currentColor), not an emoji glyph in a text layer.
4. SANS ON DISPLAY WHEN THE BRAND IS SERIF — headlines must use the theme's display family,
   not a hardcoded Inter/Roboto/system-ui dropped in by reflex.
5. ROUNDED CARD + COLORED LEFT-BORDER — the canonical "AI dashboard tile". Drop the radius
   OR the left stripe; don't ship the cliché pair.
6. INVENTED METRICS — "10× faster", "99.9% uptime", "3× more productive" with no source.
   Use a real number from the brief or a clearly-labelled placeholder.
7. FILLER COPY — lorem ipsum, "Feature one/two/three", "placeholder text", "sample content".
   An empty slot is a COMPOSITION problem to solve, not an excuse to invent words.

## Soft tells (P1 — should fix)
  • The stock skeleton: Hero → Features → Pricing → FAQ → CTA with zero variation. Break it —
    one unconventional section (a full-bleed quote, a compare-against-the-status-quo block).
  • >12 raw hex values where tokens should be — the theme wasn't honored.
  • The accent used 6+ times on one surface — cap at ~2 visible uses (one eyebrow/chip + one CTA).
  • Decorative blob/wave backgrounds — meaningless geometry; cut it or make it carry meaning.
  • Perfect symmetry with no tension — alternate density (one tight block, one breathing block).

## Add soul without breaking rules
See the 80/20 rule + identifiability test in get_engine_guide({section:"craft"}). One bold
move, real voice, one product-specific detail. If it could be any brand's, redesign.`,

  color: `# Color craft — using the palette well (the theme supplies it; this is HOW)

## A coherent palette has four layers — plan all four before placing fills
  • NEUTRALS  70–90% of pixels — bg, surface, text, muted, border.
  • ACCENT    5–10% — ONE accent only. Never invent a second.
  • SEMANTIC  0–5% — success/warn/danger, only where state demands it.
  • EFFECT    <1% — gradients, glows; rarely justified, never the default look.

## Accent discipline (the #1 readability failure in AI output is accent overuse)
  • At most ~2 VISIBLE accent uses per surface. Typical pair: one eyebrow/chip + one CTA.
    Or one accent panel + one highlighted number. Pick a pair, not a flood.
  • Links/hover/focus rings COUNT as accent uses — ration them.
  • A whole-canvas accent fill is not "bold", it's noise. Let neutrals hold the field and
    the accent earn attention by scarcity.

## Contrast — run as GATES, not goals (design-lint enforces ~2:1 hard-floor; aim higher)
  • Body text on its background: ≥ 4.5:1.
  • Large/display text (≥24px bold or ≥32px): ≥ 3:1.
  • A colored chip behind text must be WIDER than the text and meet the same contrast — a chip
    narrower than its label lets the text spill onto the canvas and vanish.

## Avoid the tells
  • Don't reach for a gradient to add "richness" — a flat surface + a pattern/texture fill (dots,
    grid, halftone, blueprint…) or a duotone photo reads more designed and never muddies text.
  • Two-stop purple→blue is the AI gradient. If you must gradient, keep it tonal (one hue, light→dark)
    and off the text.
  • Pull the palette from the brief's brand/mood words; a navy-on-white default is the safe-but-samey trap.`,

  type: `# Typography craft — hierarchy that reads AUTHORED, not assembled

## The core contract — every typographic surface satisfies all three
  1. ONE dominant entry point. The eye needs ONE place to start — one element wins. If two
     or three things compete at the same weight, nothing leads.
  2. Intentional RHYTHM between levels. Hierarchy is the CONTRAST between sizes, not a list of
     sizes. Adjacent levels too close in size/weight/spacing read flat. The headline should be
     ~3–5× the body, not 1.5×.
  3. Recoverable flow. You may invert/collapse hierarchy for tension, but a reader must still
     reconstruct the structure without re-reading. Tension, not chaos.

## Scale + tracking rules (universal, regardless of font)
  • ALL-CAPS always needs ≥0.06em letter-spacing (tracking) — caps without tracking is a tell.
  • Large display text wants TIGHT tracking (slightly negative) + tight line-height (~1.0–1.1).
  • Body wants NORMAL tracking + open line-height (~1.4–1.6) for sustained reading.
  • Don't ship 6 sizes that are all close — collapse to a clear ladder: display / heading /
    body / caption. Four well-separated levels beat eight mushy ones.

## Pairing + weight
  • One display family + one text family is plenty. A third font is almost always a mistake.
  • 600 is a strong, quiet emphasis weight; reserve 700+ for true display moments; 300 only for
    large contrast lines, never body.
  • Emphasis = weight or size or color — pick ONE lever per moment, not all three at once.

## The editorial move (the 20% soul, often)
A single oversized headline with generous margin, or a number set huge against small labels,
carries a poster on its own. Type IS the design more often than decoration is.`,

  ux_laws: `# Laws of UX — what to COMPOSE (cognitive limits, named research)

The theme decides look; craft/color/type decide rendering; THIS decides composition —
how many choices fit, where the eye lands, when an element earns its place.

  • HICK'S LAW — decision time grows with the number + complexity of choices. Pricing with 6
    tiers paralyzes; 3 converts. Cut options to the essential set; defer the rest.
  • MILLER 7±2 / COWAN ~4 — working memory holds ~4 chunks. Group nav, stats, features into
    sets of 3–5; never a flat list of 12. Use proximity + headers to chunk.
  • FITTS'S LAW — time-to-target scales with distance ÷ size. The primary action should be big
    and where scanning lands (end of the content flow, not buried). Don't make the CTA tiny.
  • VON RESTORFF (isolation) — the one different item is remembered. Make the primary tier/CTA
    visually distinct (the legitimate use of the single accent). If everything pops, nothing does.
  • PROXIMITY / COMMON REGION (Gestalt) — related things sit close / share a container; unrelated
    things get whitespace or a divider. Spacing is structure, not leftover.
  • PEAK-END — people judge an experience by its most intense moment + its end. Give a deck/report
    ONE memorable peak (a hero stat, a bold cover) and a strong closing slide, not a flat middle.
  • ZEIGARNIK / GOAL-GRADIENT — progress that looks unfinished pulls completion. A 3-of-5 progress
    bar or a checklist with momentum beats a wall of equal items (onboarding, multi-step).

Apply by SUBTRACTION first: fewer choices, tighter groups, one clear anchor. Most AI layouts
fail by adding, not by lacking.`,

  a11y: `# Accessibility baseline — for any INTERACTIVE output (reports, Mode B, decks)

Static posters: the color-contrast gates (→ color) are the relevant ones. Interactive
artifacts (interactive_table, filter_bar, button, tabs, modal…) must also clear these:

  • CONTRAST — body ≥4.5:1, large text/UI glyphs ≥3:1, focus ring ≥3:1 against its neighbor.
  • FOCUS — every interactive control is keyboard-reachable and shows a VISIBLE focus state.
    Never remove the outline without replacing it with a clear ring.
  • LABELS — every control has an accessible name (a button that's an icon needs a label;
    a filter needs a legend). Don't rely on color or position alone to convey meaning.
  • HIT TARGET — interactive targets ≥ ~44px so they're tappable (Fitts again).
  • STATE — show loading / empty / error / selected states, not only the happy path. An empty
    table needs an empty-state message, not a blank void.
  • MOTION — keep transitions short (≤300ms) and avoid large persistent motion; respect that
    some users disable it. Motion guides attention, it isn't decoration.

These are gates, not goals — an interactive report that fails them is broken, not "less polished".`,
};

/** Slugs that map onto a craft rulebook (excludes the `craft` index itself). */
export const CRAFT_MODULES = ['anti_slop', 'color', 'type', 'ux_laws', 'a11y'] as const;

/** All craft section slugs (index + modules), for the guide section enum. */
export const CRAFT_SECTIONS = Object.keys(CRAFT);

/** A craft rulebook by slug, or null if unknown. */
export function craft(slug: string): string | null {
  return CRAFT[slug] ?? null;
}

/**
 * The craft modules relevant to a design KIND, so a caller can inject only what
 * earns its token cost (mirrors OD's `od.craft.requires`). Color + type apply to
 * everything that emits styled type; anti_slop to anything that risks the AI look;
 * ux_laws + a11y only when there's real composition density / interactivity.
 */
export function craftFor(kind: string): string[] {
  const k = kind.toLowerCase();
  const base = ['color', 'type', 'anti_slop'];
  if (/report|dashboard|interactive|app|form|table/.test(k)) return [...base, 'ux_laws', 'a11y'];
  if (/deck|presentation|slide|carousel|pitch/.test(k)) return [...base, 'ux_laws'];
  if (/poster|card|cover|flyer|banner|social/.test(k)) return base;
  return base;
}
