// Raster-export font support. PNG/PDF go through resvg, which can't fetch web
// fonts — it only sees fonts we hand it. We bundle a curated set of the families
// Folio steers designs toward (src/mcp/fonts/*.ttf) and point resvg at the whole
// directory so the raster output matches the editor's web-font render.
//
// manifest.json (generated by scripts/gen-font-manifest.mjs from the TTF name
// tables) lists which families are actually bundled, so the engine can warn when
// a design uses a family that ISN'T — it would silently fall back to DejaVu in
// export while rendering fine in the editor.
import * as fs from 'fs';
import * as path from 'path';
import { libraryRoot } from './asset-library';

const FONTS_DIR = path.resolve(process.cwd(), 'src/mcp/fonts');

/** Absolute path to the bundled-fonts directory (handed to resvg via fontDirs). */
export function fontsDir(): string {
  return FONTS_DIR;
}

let _families: Set<string> | null = null;
/** Lowercased family names bundled for raster export (cached). */
export function bundledFamilies(): Set<string> {
  if (_families) return _families;
  const out = new Set<string>();
  try {
    const raw = fs.readFileSync(path.join(FONTS_DIR, 'manifest.json'), 'utf8');
    const m = JSON.parse(raw) as { families?: string[] };
    for (const f of m.families ?? []) out.add(f.toLowerCase());
  } catch {
    // No manifest (older image / fonts not fetched) — leave empty; callers then
    // simply skip the unbundled-font warning rather than crash.
  }
  _families = out;
  return out;
}

// ── Project fonts (WP-1.6) — TTF/OTF the operator uploaded to
//    <project>/assets/fonts. resvg reads the real name tables, so rendering is
//    exact; only the unbundled-WARNING heuristic below is filename-based.

/** `<project>/assets/fonts` when it exists, else null. */
export function projectFontsDir(projectDir?: string): string | null {
  if (!projectDir) return null;
  const d = path.join(projectDir, 'assets', 'fonts');
  try { return fs.statSync(d).isDirectory() ? d : null; } catch { return null; }
}

export { fontFamilyFromFilename } from '../../utils/font-name';
import { fontFamilyFromFilename, isFontFile } from '../../utils/font-name';
import { readFontNames } from '../../utils/font-name-table';

/**
 * Every project font file with the family names it answers to.
 *
 * The filename guess alone is not enough. A downloaded family often declares
 * itself something the filename never said — Fontsource ships Space Grotesk's
 * static weights as "Space Grotesk Light", the variable font's default
 * instance — and resvg matches on the DECLARED name. So both are registered:
 * the declared one (which is what actually renders) and the filename guess
 * (which is what an operator who renamed the file will type).
 *
 * Cached on path+mtime+size: reading a 300 KiB TTF per render otherwise.
 */
const nameCache = new Map<string, { key: string; families: string[]; weight?: number }>();

export interface ProjectFont { file: string; families: string[]; weight?: number }

/** One font file → the families it answers to, or null when it names nothing. */
function readFontEntry(abs: string, file: string): ProjectFont | null {
  {
    const f = file;
    const families = new Set<string>();
    const guess = fontFamilyFromFilename(f);
    if (guess) families.add(guess);
    let weight: number | undefined;
    try {
      const st = fs.statSync(abs);
      const key = `${st.mtimeMs}:${st.size}`;
      const hit = nameCache.get(abs);
      const names = hit?.key === key ? hit : null;
      if (names) {
        for (const fam of names.families) families.add(fam);
        weight = names.weight;
      } else {
        const parsed = readFontNames(fs.readFileSync(abs));
        const declared = parsed.family ? [parsed.family.toLowerCase()] : [];
        for (const fam of declared) families.add(fam);
        weight = parsed.weightClass;
        const entry: { key: string; families: string[]; weight?: number } = { key, families: declared };
        if (weight !== undefined) entry.weight = weight;
        nameCache.set(abs, entry);
      }
    } catch { /* unreadable/malformed → the filename guess stands alone */ }
    if (!families.size) return null;
    return weight === undefined
      ? { file: abs, families: [...families] }
      : { file: abs, families: [...families], weight };
  }
}

export function projectFontEntries(projectDir?: string): ProjectFont[] {
  const pd = projectFontsDir(projectDir);
  if (!pd) return [];
  let files: string[];
  try { files = fs.readdirSync(pd); } catch { return []; }
  const out: ProjectFont[] = [];
  for (const f of files) {
    if (!isFontFile(f)) continue;
    const entry = readFontEntry(path.join(pd, f), f);
    if (entry) out.push(entry);
  }
  return out;
}

/**
 * Fonts in the SHARED library. They can sit at any depth in the tree (the
 * library files by vendor/topic, not by kind), so this walks rather than reads
 * one directory.
 */
export function libraryFontEntries(): ProjectFont[] {
  const out: ProjectFont[] = [];
  const walk = (dir: string, depth: number): void => {
    if (depth > 6) return;
    let entries: fs.Dirent[];
    try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const e of entries) {
      if (e.isDirectory()) { if (!e.name.startsWith('.')) walk(path.join(dir, e.name), depth + 1); continue; }
      if (!e.isFile() || !isFontFile(e.name)) continue;
      const entry = readFontEntry(path.join(dir, e.name), e.name);
      if (entry) out.push(entry);
    }
  };
  walk(libraryRoot(), 1);
  return out;
}

/** Lowercased family names every project AND shared-library font answers to. */
export function projectFontFamilies(projectDir?: string): Set<string> {
  const out = new Set<string>();
  for (const e of [...projectFontEntries(projectDir), ...libraryFontEntries()]) {
    for (const f of e.families) out.add(f);
  }
  return out;
}

/** resvg `font` option: bundled dir (+ the project's assets/fonts when given)
 *  + system fonts, DejaVu as last resort. */
export function resvgFontOption(projectDir?: string): {
  fontDirs: string[];
  loadSystemFonts: boolean;
  defaultFontFamily: string;
} {
  const dirs = [FONTS_DIR];
  const pd = projectFontsDir(projectDir);
  if (pd) dirs.push(pd);
  // Shared-library fonts. resvg's font database walks a font dir recursively,
  // so pointing at the library root once covers the whole nested tree.
  const lib = libraryRoot();
  try { if (fs.statSync(lib).isDirectory()) dirs.push(lib); } catch { /* no library yet */ }
  return { fontDirs: dirs, loadSystemFonts: true, defaultFontFamily: 'DejaVu Sans' };
}

const GENERIC = new Set([
  'sans-serif', 'serif', 'monospace', 'system-ui', 'ui-monospace', 'ui-sans-serif',
  'ui-serif', 'cursive', 'fantasy', 'inherit', 'dejavu sans',
]);

/**
 * Families referenced in an SVG string that are NOT bundled for raster export
 * (deduped, generics excluded). Empty when every referenced font is available —
 * or when no manifest is present.
 */
export function unbundledFonts(svg: string, projectDir?: string): string[] {
  const have = bundledFamilies();
  if (have.size === 0) return [];
  const project = projectFontFamilies(projectDir);
  const seen = new Set<string>();
  const missing: string[] = [];
  const re = /font-family="([^"]+)"/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(svg)) !== null) {
    // a font-family attr can be a stack ("Inter, sans-serif") — check the first.
    const fam = m[1].split(',')[0].trim().replace(/^['"]|['"]$/g, '');
    const key = fam.toLowerCase();
    if (!fam || GENERIC.has(key) || seen.has(key)) continue;
    seen.add(key);
    if (!have.has(key) && !project.has(key)) missing.push(fam);
  }
  return missing;
}
