// Raster-export font support. PNG/PDF go through resvg, which can't fetch web
// fonts — it only sees fonts we hand it. We bundle a curated set of the families
// Folio steers designs toward (src/mcp/fonts/*.ttf) and point resvg at the whole
// directory so the raster output matches the editor's web-font render.
//
// manifest.json (generated by scripts/gen-font-manifest.mjs from the TTF name
// tables) lists which families are actually bundled, so the engine can warn when
// a design uses a family that ISN'T — it would silently fall back to DejaVu in
// export while rendering fine in the editor.
import * as fs from 'fs';
import * as path from 'path';

const FONTS_DIR = path.resolve(process.cwd(), 'src/mcp/fonts');

/** Absolute path to the bundled-fonts directory (handed to resvg via fontDirs). */
export function fontsDir(): string {
  return FONTS_DIR;
}

let _families: Set<string> | null = null;
/** Lowercased family names bundled for raster export (cached). */
export function bundledFamilies(): Set<string> {
  if (_families) return _families;
  const out = new Set<string>();
  try {
    const raw = fs.readFileSync(path.join(FONTS_DIR, 'manifest.json'), 'utf8');
    const m = JSON.parse(raw) as { families?: string[] };
    for (const f of m.families ?? []) out.add(f.toLowerCase());
  } catch {
    // No manifest (older image / fonts not fetched) — leave empty; callers then
    // simply skip the unbundled-font warning rather than crash.
  }
  _families = out;
  return out;
}

/** resvg `font` option: load the bundled dir + system fonts, DejaVu as last resort. */
export function resvgFontOption(): {
  fontDirs: string[];
  loadSystemFonts: boolean;
  defaultFontFamily: string;
} {
  return { fontDirs: [FONTS_DIR], loadSystemFonts: true, defaultFontFamily: 'DejaVu Sans' };
}

const GENERIC = new Set([
  'sans-serif', 'serif', 'monospace', 'system-ui', 'ui-monospace', 'ui-sans-serif',
  'ui-serif', 'cursive', 'fantasy', 'inherit', 'dejavu sans',
]);

/**
 * Families referenced in an SVG string that are NOT bundled for raster export
 * (deduped, generics excluded). Empty when every referenced font is available —
 * or when no manifest is present.
 */
export function unbundledFonts(svg: string): string[] {
  const have = bundledFamilies();
  if (have.size === 0) return [];
  const seen = new Set<string>();
  const missing: string[] = [];
  const re = /font-family="([^"]+)"/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(svg)) !== null) {
    // a font-family attr can be a stack ("Inter, sans-serif") — check the first.
    const fam = m[1].split(',')[0].trim().replace(/^['"]|['"]$/g, '');
    const key = fam.toLowerCase();
    if (!fam || GENERIC.has(key) || seen.has(key)) continue;
    seen.add(key);
    if (!have.has(key)) missing.push(fam);
  }
  return missing;
}
