// Raster-export font support. PNG/PDF go through resvg, which can't fetch web
// fonts — it only sees fonts we hand it. We bundle a curated set of the families
// Folio steers designs toward (src/mcp/fonts/*.ttf) and point resvg at the whole
// directory so the raster output matches the editor's web-font render.
//
// manifest.json (generated by scripts/gen-font-manifest.mjs from the TTF name
// tables) lists which families are actually bundled, so the engine can warn when
// a design uses a family that ISN'T — it would silently fall back to DejaVu in
// export while rendering fine in the editor.
import * as fs from 'fs';
import * as path from 'path';

const FONTS_DIR = path.resolve(process.cwd(), 'src/mcp/fonts');

/** Absolute path to the bundled-fonts directory (handed to resvg via fontDirs). */
export function fontsDir(): string {
  return FONTS_DIR;
}

let _families: Set<string> | null = null;
/** Lowercased family names bundled for raster export (cached). */
export function bundledFamilies(): Set<string> {
  if (_families) return _families;
  const out = new Set<string>();
  try {
    const raw = fs.readFileSync(path.join(FONTS_DIR, 'manifest.json'), 'utf8');
    const m = JSON.parse(raw) as { families?: string[] };
    for (const f of m.families ?? []) out.add(f.toLowerCase());
  } catch {
    // No manifest (older image / fonts not fetched) — leave empty; callers then
    // simply skip the unbundled-font warning rather than crash.
  }
  _families = out;
  return out;
}

// ── Project fonts (WP-1.6) — TTF/OTF the operator uploaded to
//    <project>/assets/fonts. resvg reads the real name tables, so rendering is
//    exact; only the unbundled-WARNING heuristic below is filename-based.

/** `<project>/assets/fonts` when it exists, else null. */
export function projectFontsDir(projectDir?: string): string | null {
  if (!projectDir) return null;
  const d = path.join(projectDir, 'assets', 'fonts');
  try { return fs.statSync(d).isDirectory() ? d : null; } catch { return null; }
}

export { fontFamilyFromFilename } from '../../utils/font-name';
import { fontFamilyFromFilename, isFontFile } from '../../utils/font-name';

/** Lowercased family guesses for every font file in the project (no cache —
 *  operators upload mid-session and the dir listing is tiny). */
export function projectFontFamilies(projectDir?: string): Set<string> {
  const out = new Set<string>();
  const pd = projectFontsDir(projectDir);
  if (!pd) return out;
  try {
    for (const f of fs.readdirSync(pd)) {
      if (!isFontFile(f)) continue;
      const fam = fontFamilyFromFilename(f);
      if (fam) out.add(fam);
    }
  } catch { /* unreadable dir → none */ }
  return out;
}

/** resvg `font` option: bundled dir (+ the project's assets/fonts when given)
 *  + system fonts, DejaVu as last resort. */
export function resvgFontOption(projectDir?: string): {
  fontDirs: string[];
  loadSystemFonts: boolean;
  defaultFontFamily: string;
} {
  const dirs = [FONTS_DIR];
  const pd = projectFontsDir(projectDir);
  if (pd) dirs.push(pd);
  return { fontDirs: dirs, loadSystemFonts: true, defaultFontFamily: 'DejaVu Sans' };
}

const GENERIC = new Set([
  'sans-serif', 'serif', 'monospace', 'system-ui', 'ui-monospace', 'ui-sans-serif',
  'ui-serif', 'cursive', 'fantasy', 'inherit', 'dejavu sans',
]);

/**
 * Families referenced in an SVG string that are NOT bundled for raster export
 * (deduped, generics excluded). Empty when every referenced font is available —
 * or when no manifest is present.
 */
export function unbundledFonts(svg: string, projectDir?: string): string[] {
  const have = bundledFamilies();
  if (have.size === 0) return [];
  const project = projectFontFamilies(projectDir);
  const seen = new Set<string>();
  const missing: string[] = [];
  const re = /font-family="([^"]+)"/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(svg)) !== null) {
    // a font-family attr can be a stack ("Inter, sans-serif") — check the first.
    const fam = m[1].split(',')[0].trim().replace(/^['"]|['"]$/g, '');
    const key = fam.toLowerCase();
    if (!fam || GENERIC.has(key) || seen.has(key)) continue;
    seen.add(key);
    if (!have.has(key) && !project.has(key)) missing.push(fam);
  }
  return missing;
}
