// WP-2.2 — Catalog packs over MCP (read-only, no new tool).
//
// The editor Catalog offers three curated pack families the model previously
// couldn't see: colour PALETTES, TYPE pairings, and EFFECTS sets. Their compact
// index JSONs (generated by scripts/gen-*-index.mjs, same files the editor
// lazy-loads) carry the actually-usable values inline — palette swatches, type
// families, effect keys — so a single index read gives a model everything it
// needs to name a pack and use it, in a few hundred tokens. Surfaced as
// `themes {op:"packs", kind, ...}`; the full .yaml bodies stay editor-only.

import * as fs from 'fs';
import * as path from 'path';
import type { ToolResult } from '../types';
import { okResult, errResult } from './utils';

const OP = 'packs';

export type PackKind = 'palette' | 'type' | 'effects';

const INDEX_FILE: Record<PackKind, string> = {
  palette: 'palette-index.json',
  type: 'type-pack-index.json',
  effects: 'effects-pack-index.json',
};

interface PackEntry {
  id: string;
  name: string;
  tags?: string[];
  description?: string;
  swatches?: string[];                       // palette
  families?: Record<string, string>;         // type
  effectKeys?: string[];                      // effects
  file?: string;
}

function indexPath(kind: PackKind): string | null {
  const candidates = [
    path.join(process.cwd(), 'src', 'styles', INDEX_FILE[kind]),
    path.join(process.cwd(), 'dist', 'styles', INDEX_FILE[kind]),
  ];
  for (const c of candidates) {
    try { if (fs.statSync(c).isFile()) return c; } catch { /* next */ }
  }
  return null;
}

let _cache: Partial<Record<PackKind, PackEntry[]>> = {};
function loadPacks(kind: PackKind): PackEntry[] {
  if (_cache[kind]) return _cache[kind] as PackEntry[];
  const p = indexPath(kind);
  if (!p) return [];
  try {
    const parsed = JSON.parse(fs.readFileSync(p, 'utf8')) as { entries?: PackEntry[] };
    const rows = Array.isArray(parsed.entries) ? parsed.entries : [];
    _cache[kind] = rows;
    return rows;
  } catch {
    return [];
  }
}

/** Test hook — drop the parsed-index cache. */
export function _resetPacks(): void { _cache = {}; }

const KINDS: PackKind[] = ['palette', 'type', 'effects'];

// The usable payload for one pack, kind-shaped. Kept minimal so a single pack
// stays well under the ~300-token budget.
function usable(kind: PackKind, e: PackEntry): Record<string, unknown> {
  const base = { id: e.id, name: e.name, tags: e.tags ?? [], description: e.description };
  if (kind === 'palette') return { ...base, swatches: e.swatches ?? [] };
  if (kind === 'type') return { ...base, families: e.families ?? {} };
  return { ...base, effect_keys: e.effectKeys ?? [] };
}

// Compact one-line-per-pack listing (no full values) for browsing.
function summary(kind: PackKind, e: PackEntry): Record<string, unknown> {
  if (kind === 'palette') return { id: e.id, name: e.name, swatches: e.swatches ?? [] };
  if (kind === 'type') return { id: e.id, name: e.name, families: e.families ?? {} };
  return { id: e.id, name: e.name, effect_keys: e.effectKeys ?? [] };
}

function matches(e: PackEntry, q: string): boolean {
  const hay = `${e.id} ${e.name} ${(e.tags ?? []).join(' ')} ${e.description ?? ''}`.toLowerCase();
  return q.split(/\s+/).filter(Boolean).every(t => hay.includes(t));
}

function ok(data: Record<string, unknown>, next?: string): ToolResult {
  return okResult(OP, next ? { ...data, next_action: next } : data);
}
function err(msg: string, hint: string): ToolResult {
  return errResult(OP, msg, hint);
}

/**
 * `themes {op:"packs"}` — read-only catalog packs.
 *  - no `kind`        → the three kinds + their counts (discovery).
 *  - `kind` + `id`    → one pack's full usable values (hexes / families / keys).
 *  - `kind` [+search] → filtered compact listing (id + name + values).
 */
export function listPacks(a: {
  kind?: string; id?: string; search?: string; limit?: number;
}): ToolResult {
  const kind = a.kind as PackKind | undefined;

  if (!kind) {
    const counts = KINDS.map(k => ({ kind: k, count: loadPacks(k).length }));
    return ok({
      packs: counts,
      usage: 'themes {op:"packs", kind:"palette|type|effects"} to list; add id:"…" for one pack\'s values, or search:"…" to filter.',
    });
  }
  if (!KINDS.includes(kind)) {
    return err(`unknown pack kind "${a.kind}"`, `kind must be one of: ${KINDS.join(', ')}.`);
  }

  const rows = loadPacks(kind);
  if (rows.length === 0) return err(`no ${kind} packs available`, 'the pack index file is missing from this build.');

  if (a.id) {
    const hit = rows.find(e => e.id === a.id);
    if (!hit) return err(`no ${kind} pack "${a.id}"`, `omit id to list ${kind} packs.`);
    const applyHint = kind === 'palette'
      ? 'Use these hexes directly as layer fills/colors, or as a theme palette.'
      : kind === 'type'
        ? 'Set these as heading/body/mono font families (or the theme typography).'
        : 'Apply these effect keys via a layer\'s effect field.';
    return ok(usable(kind, hit), applyHint);
  }

  const q = (a.search ?? '').trim().toLowerCase();
  let list = q ? rows.filter(e => matches(e, q)) : rows;
  const total = list.length;
  const limit = Math.max(1, Math.min(a.limit ?? 24, 60));
  list = list.slice(0, limit);
  return ok({
    kind,
    total,
    shown: list.length,
    packs: list.map(e => summary(kind, e)),
  }, `themes {op:"packs", kind:"${kind}", id:"<id>"} for one pack's full values.`);
}
